// The schema as the plans define it (architecture 3, B2 Data changes; sketch columns as B2 Inputs defines them), one
// entry per column, compared with information_schema by schema.db.test.ts. A type is the data_type Postgres reports,
// with these spellings: an enum by its name, an array as `<element>[]`, `numeric(p,s)`, `char(n)`, `timestamptz`.
// A trailing `?` marks a nullable column. A slice that adds a table or a column adds it here in the same commit.

export const schemaManifest: Record<string, Record<string, string>> = {
  migration_checksums: {
    version: "text",
    sha256: "text",
    pushed_at: "timestamptz",
  },
  user_roles: {
    id: "uuid",
    user_id: "uuid",
    role: "app_role",
    actor_kind: "actor_kind",
    display_name: "text?",
    disabled_at: "timestamptz?",
    created_at: "timestamptz",
    updated_at: "timestamptz",
  },
  agent_keys: {
    id: "uuid",
    user_id: "uuid",
    key_hash: "text",
    label: "text",
    scopes: "text[]",
    last_used_at: "timestamptz?",
    revoked_at: "timestamptz?",
    created_at: "timestamptz",
  },
  audit_log: {
    id: "bigint",
    at: "timestamptz",
    actor_id: "uuid?",
    actor_kind: "actor_kind?",
    action: "text",
    entity: "text",
    entity_id: "uuid?",
    before: "jsonb?",
    after: "jsonb?",
    request_id: "text?",
    note: "text?",
  },
  pii_columns: {
    table_name: "text",
    column_name: "text",
  },
  markets: {
    slug: "text",
    name: "text",
    country: "text",
    currency: "char(3)",
    intro: "text",
    places: "text[]",
    image: "text?",
    image_variants: "jsonb",
    sort_order: "integer",
    coming_soon: "boolean",
    interest_copy: "text?",
    created_at: "timestamptz",
    updated_at: "timestamptz",
  },
  regions: {
    slug: "text",
    market_slug: "text",
    name: "text",
    intro: "text",
    places: "text[]",
    image: "text?",
    image_variants: "jsonb",
    sort_order: "integer",
    created_at: "timestamptz",
    updated_at: "timestamptz",
  },
  market_notes: {
    id: "uuid",
    market_slug: "text",
    label: "text",
    text: "text",
    sort_order: "integer",
    created_at: "timestamptz",
    updated_at: "timestamptz",
  },
  market_guide_entries: {
    id: "uuid",
    market_slug: "text",
    section: "text",
    region_slug: "text?",
    label: "text",
    text: "text",
    sort_order: "integer",
    created_at: "timestamptz",
    updated_at: "timestamptz",
  },
  representatives: {
    id: "uuid",
    name: "text",
    brokerage: "text",
    license: "text?",
    email: "text?",
    phone: "text?",
    photo: "text?",
    created_at: "timestamptz",
    updated_at: "timestamptz",
  },
  properties: {
    id: "uuid",
    slug: "text",
    title: "text",
    market_slug: "text",
    region_slug: "text?",
    city: "text",
    neighborhood: "text?",
    state: "text",
    country: "text?",
    address: "text",
    coordinates: "point?",
    price: "numeric(12,2)?",
    currency: "char(3)",
    beds: "integer?",
    baths: "numeric(3,1)?",
    interior_sq_ft: "integer?",
    lot_acres: "numeric(8,2)?",
    year_built: "integer?",
    type: "property_type",
    style: "text?",
    architect: "text?",
    designer: "text?",
    status: "listing_status",
    hero_image: "text?",
    video: "jsonb?",
    story: "text[]",
    place: "text?",
    representative_id: "uuid?",
    listing_url: "text?",
    hero_rank: "integer?",
    featured_rank: "integer?",
    campaign_tier: "campaign_tier",
    source: "submission_source",
    submission_id: "uuid?",
    presented_by_owner: "boolean",
    og_image_key: "text?",
    editorial_state: "editorial_state",
    published_at: "timestamptz?",
    first_published_at: "timestamptz?",
    archived_at: "timestamptz?",
    taken_down_at: "timestamptz?",
    unpublish_reason: "text?",
    unpublished_at: "timestamptz?",
    version: "integer",
    preview_nonce: "uuid",
    search_text: "tsvector?",
    created_by: "uuid?",
    updated_by: "uuid?",
    created_at: "timestamptz",
    updated_at: "timestamptz",
  },
  property_media: {
    id: "uuid",
    property_id: "uuid",
    media_key: "text?",
    staging_path: "text?",
    variants: "jsonb",
    alt: "text?",
    orientation: "media_orientation?",
    sort_order: "integer",
    render_job_id: "uuid?",
    created_at: "timestamptz",
    updated_at: "timestamptz",
  },
  property_features: {
    property_id: "uuid",
    feature: "text",
    sort_order: "integer",
    created_at: "timestamptz",
    updated_at: "timestamptz",
  },
  property_related: {
    property_id: "uuid",
    related_slug: "text",
    sort_order: "integer",
    created_at: "timestamptz",
    updated_at: "timestamptz",
  },
  stories: {
    id: "uuid",
    slug: "text",
    title: "text",
    deck: "text",
    category: "story_category",
    market_slug: "text",
    image: "text?",
    image_variants: "jsonb",
    body: "text[]",
    properties: "text[]",
    editorial_state: "editorial_state",
    published_at: "timestamptz?",
    archived_at: "timestamptz?",
    author_id: "uuid?",
    created_at: "timestamptz",
    updated_at: "timestamptz",
  },
  settings: {
    key: "text",
    value: "jsonb",
    updated_at: "timestamptz",
    updated_by: "uuid?",
  },
  slug_history: {
    slug: "text",
    property_id: "uuid",
    changed_at: "timestamptz",
  },
  redirects: {
    id: "uuid",
    from_path: "text",
    to_path: "text",
    status: "smallint",
    enabled: "boolean",
    note: "text?",
    archived_at: "timestamptz?",
    created_by: "uuid?",
    created_at: "timestamptz",
    updated_at: "timestamptz",
  },
  retention_policies: {
    key: "text",
    table_name: "text",
    keep_for: "interval?",
    action: "text",
    enabled: "boolean",
    note: "text?",
    updated_by: "uuid?",
    updated_at: "timestamptz",
  },
  decline_reasons: {
    id: "uuid",
    code: "text",
    label: "text",
    email_paragraph: "text",
    sort: "integer",
    enabled: "boolean",
  },
  contacts: {
    id: "uuid",
    kind: "submitter_kind",
    name: "text",
    email: "text",
    phone: "text?",
    brokerage: "text?",
    notes: "text?",
    created_at: "timestamptz",
    updated_at: "timestamptz",
    archived_at: "timestamptz?",
  },
  submissions: {
    id: "uuid",
    address: "text",
    city: "text",
    state: "accepted_state",
    zip: "char(5)",
    listing_url: "text?",
    source_url: "text?",
    price: "numeric(12,2)?",
    currency: "char(3)",
    property_type: "property_type",
    beds: "integer?",
    baths: "numeric(3,1)?",
    interior_sq_ft: "integer?",
    architect: "text?",
    designer: "text?",
    year_built: "integer?",
    year_renovated: "integer?",
    brokerage: "text?",
    submitter_kind: "submitter_kind",
    submitter_name: "text",
    submitter_email: "text",
    submitter_phone: "text?",
    listed_with_agent: "boolean?",
    listing_agent_name: "text?",
    listing_agent_brokerage: "text?",
    contact_id: "uuid?",
    photography_url: "text?",
    video_url: "text?",
    story: "text",
    significance: "text",
    package: "exposure_package",
    media_budget: "numeric(12,2)?",
    source_path: "text",
    workflow_state: "submission_state",
    reviewed_by: "uuid?",
    reviewed_at: "timestamptz?",
    decline_reason_id: "uuid?",
    decline_note: "text?",
    accepted_by: "uuid?",
    accepted_at: "timestamptz?",
    activated_by: "uuid?",
    activated_at: "timestamptz?",
    property_id: "uuid?",
    notes: "jsonb[]",
    turnstile_ok: "boolean",
    ip_hash: "text?",
    received_at: "timestamptz",
    rights_version: "text",
    rights_confirmed_at: "timestamptz",
    rights_ip_hash: "text",
  },
  submission_media: {
    id: "uuid",
    submission_id: "uuid",
    name: "text",
    storage_path: "text",
    uploaded_at: "timestamptz?",
    bytes: "bigint?",
    mime: "text?",
    sha256: "text?",
  },
  inquiries: {
    id: "uuid",
    intent: "inquiry_intent",
    topic: "text?",
    subject_kind: "text?",
    subject_slug: "text?",
    subject_title: "text?",
    name: "text",
    email: "text",
    phone: "text?",
    location: "text?",
    message: "text",
    details: "jsonb",
    source_path: "text",
    state: "inquiry_state",
    forwarded_at: "timestamptz?",
    received_at: "timestamptz",
    ip_hash: "text?",
    assigned_to: "uuid?",
    forwarded_payload: "jsonb?",
    turnstile_ok: "boolean",
  },
  subscribers: {
    id: "uuid",
    email: "text",
    source: "text",
    markets: "text[]",
    confirmed_at: "timestamptz?",
    confirm_token_hash: "text?",
    unsubscribed_at: "timestamptz?",
    resend_contact_id: "text?",
    archived_at: "timestamptz?",
    created_at: "timestamptz",
    updated_at: "timestamptz",
  },
  // The parent of the monthly partitions (migration 6); the partitions themselves are not tables of the manifest.
  analytics_events: {
    id: "bigint",
    event: "text",
    path: "text",
    data: "jsonb",
    occurred_at: "timestamptz",
    received_at: "timestamptz",
  },
};

/** Every money column, each `numeric(12,2)` with a currency check (STANDARDS R24). */
export const moneyColumns = ["properties.price", "submissions.price", "submissions.media_budget"];

/**
 * `table.column` names that match the personal-data pattern of invariant 18 and hold none. Later slices append
 * theirs.
 */
export const notPii = [
  "markets.name",
  "regions.name",
  "representatives.name",
  "properties.address",
  "submission_media.name",
  "user_roles.display_name",
  "pii_columns.table_name",
  "pii_columns.column_name",
  "retention_policies.table_name",
  "decline_reasons.email_paragraph",
];
