// Generated by scripts/gen-theme.ts from src/styles/tokens.css. Do not edit.
// Regenerate with: bun run scripts/gen-theme.ts

export const themeHex = {
  background: "#f5f2eb",
  foreground: "#11110f",
  secondary: "#eeeae1",
  mutedForeground: "#575751",
  accent: "#c9c0b2",
} as const;

/** The same colours as 0 to 1 triples, for pdf-lib. */
export const themeRgb = {
  background: [0.9608, 0.949, 0.9216],
  foreground: [0.0667, 0.0667, 0.0588],
  secondary: [0.9333, 0.9176, 0.8824],
  mutedForeground: [0.3412, 0.3412, 0.3176],
  accent: [0.7882, 0.7529, 0.698],
} as const;
