/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteMarketRouteImport } from './routes/_site.$market'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteEditorialStandardRouteImport } from './routes/_site.editorial-standard'
import { Route as SiteExposureRouteImport } from './routes/_site.exposure'
import { Route as SiteFaqRouteImport } from './routes/_site.faq'
import { Route as SiteLegalRouteImport } from './routes/_site.legal'
import { Route as SiteMarketsRouteImport } from './routes/_site.markets'
import { Route as SitePlaceNotesRouteImport } from './routes/_site.place-notes'
import { Route as SitePricingRouteImport } from './routes/_site.pricing'
import { Route as SitePropertiesRouteImport } from './routes/_site.properties'
import { Route as SiteStoriesRouteImport } from './routes/_site.stories'
import { Route as SiteSubmitRouteImport } from './routes/_site.submit'
import { Route as MediaSplatRouteImport } from './routes/media.$'
import { Route as SiteMarketIndexRouteImport } from './routes/_site.$market.index'
import { Route as SiteMarketRegionRouteImport } from './routes/_site.$market.$region'
import { Route as SiteMarketGuideRouteImport } from './routes/_site.$market.guide'
import { Route as SiteMarketsIndexRouteImport } from './routes/_site.markets.index'
import { Route as SiteMarketsSplatRouteImport } from './routes/_site.markets.$'
import { Route as SitePropertySlugRouteImport } from './routes/_site.property.$slug'
import { Route as SiteStoriesIndexRouteImport } from './routes/_site.stories.index'
import { Route as SiteStoriesSlugRouteImport } from './routes/_site.stories.$slug'
import { Route as ApiHooksResendRouteImport } from './routes/api/hooks/resend'
import { Route as ApiHooksSentryTestRouteImport } from './routes/api/hooks/sentry-test'
import { Route as ApiPublicClientErrorRouteImport } from './routes/api/public/client-error'
import { Route as ApiPublicConciergeRouteImport } from './routes/api/public/concierge'
import { Route as ApiPublicEventsRouteImport } from './routes/api/public/events'
import { Route as ApiPublicInquiriesRouteImport } from './routes/api/public/inquiries'
import { Route as ApiPublicMarketsRouteImport } from './routes/api/public/markets'
import { Route as ApiPublicPropertiesRouteImport } from './routes/api/public/properties'
import { Route as ApiPublicSearchRouteImport } from './routes/api/public/search'
import { Route as ApiPublicStoriesRouteImport } from './routes/api/public/stories'
import { Route as ApiPublicSubmissionsRouteImport } from './routes/api/public/submissions'
import { Route as ApiPublicSubscribersRouteImport } from './routes/api/public/subscribers'
import { Route as SiteArchiveKindSlugRouteImport } from './routes/_site.archive.$kind.$slug'
import { Route as ApiHooksOpsHealthTokenRouteImport } from './routes/api/hooks/ops-health.$token'
import { Route as ApiHooksRenderCallbackRouteImport } from './routes/api/hooks/render.callback'
import { Route as ApiPublicMarketsSlugRouteImport } from './routes/api/public/markets.$slug'
import { Route as ApiPublicPropertiesSlugRouteImport } from './routes/api/public/properties.$slug'
import { Route as ApiPublicStoriesSlugRouteImport } from './routes/api/public/stories.$slug'
import { Route as ApiPublicSubjectsRequestRouteImport } from './routes/api/public/subjects.request'
import { Route as ApiPublicSubscribersConfirmRouteImport } from './routes/api/public/subscribers.confirm'
import { Route as ApiPublicSubmissionsIdUploadsRouteImport } from './routes/api/public/submissions.$id.uploads'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteMarketRoute = SiteMarketRouteImport.update({
  id: '/$market',
  path: '/$market',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEditorialStandardRoute = SiteEditorialStandardRouteImport.update({
  id: '/editorial-standard',
  path: '/editorial-standard',
  getParentRoute: () => SiteRoute,
} as any)
const SiteExposureRoute = SiteExposureRouteImport.update({
  id: '/exposure',
  path: '/exposure',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFaqRoute = SiteFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLegalRoute = SiteLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => SiteRoute,
} as any)
const SiteMarketsRoute = SiteMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => SiteRoute,
} as any)
const SitePlaceNotesRoute = SitePlaceNotesRouteImport.update({
  id: '/place-notes',
  path: '/place-notes',
  getParentRoute: () => SiteRoute,
} as any)
const SitePricingRoute = SitePricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => SiteRoute,
} as any)
const SitePropertiesRoute = SitePropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => SiteRoute,
} as any)
const SiteStoriesRoute = SiteStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSubmitRoute = SiteSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => SiteRoute,
} as any)
const MediaSplatRoute = MediaSplatRouteImport.update({
  id: '/media/$',
  path: '/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteMarketIndexRoute = SiteMarketIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteMarketRoute,
} as any)
const SiteMarketRegionRoute = SiteMarketRegionRouteImport.update({
  id: '/$region',
  path: '/$region',
  getParentRoute: () => SiteMarketRoute,
} as any)
const SiteMarketGuideRoute = SiteMarketGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => SiteMarketRoute,
} as any)
const SiteMarketsIndexRoute = SiteMarketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteMarketsRoute,
} as any)
const SiteMarketsSplatRoute = SiteMarketsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SiteMarketsRoute,
} as any)
const SitePropertySlugRoute = SitePropertySlugRouteImport.update({
  id: '/property/$slug',
  path: '/property/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteStoriesIndexRoute = SiteStoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteStoriesRoute,
} as any)
const SiteStoriesSlugRoute = SiteStoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SiteStoriesRoute,
} as any)
const ApiHooksResendRoute = ApiHooksResendRouteImport.update({
  id: '/api/hooks/resend',
  path: '/api/hooks/resend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHooksSentryTestRoute = ApiHooksSentryTestRouteImport.update({
  id: '/api/hooks/sentry-test',
  path: '/api/hooks/sentry-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClientErrorRoute = ApiPublicClientErrorRouteImport.update({
  id: '/api/public/client-error',
  path: '/api/public/client-error',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConciergeRoute = ApiPublicConciergeRouteImport.update({
  id: '/api/public/concierge',
  path: '/api/public/concierge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEventsRoute = ApiPublicEventsRouteImport.update({
  id: '/api/public/events',
  path: '/api/public/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInquiriesRoute = ApiPublicInquiriesRouteImport.update({
  id: '/api/public/inquiries',
  path: '/api/public/inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMarketsRoute = ApiPublicMarketsRouteImport.update({
  id: '/api/public/markets',
  path: '/api/public/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPropertiesRoute = ApiPublicPropertiesRouteImport.update({
  id: '/api/public/properties',
  path: '/api/public/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSearchRoute = ApiPublicSearchRouteImport.update({
  id: '/api/public/search',
  path: '/api/public/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStoriesRoute = ApiPublicStoriesRouteImport.update({
  id: '/api/public/stories',
  path: '/api/public/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSubmissionsRoute = ApiPublicSubmissionsRouteImport.update({
  id: '/api/public/submissions',
  path: '/api/public/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSubscribersRoute = ApiPublicSubscribersRouteImport.update({
  id: '/api/public/subscribers',
  path: '/api/public/subscribers',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteArchiveKindSlugRoute = SiteArchiveKindSlugRouteImport.update({
  id: '/archive/$kind/$slug',
  path: '/archive/$kind/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const ApiHooksOpsHealthTokenRoute = ApiHooksOpsHealthTokenRouteImport.update({
  id: '/api/hooks/ops-health/$token',
  path: '/api/hooks/ops-health/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHooksRenderCallbackRoute = ApiHooksRenderCallbackRouteImport.update({
  id: '/api/hooks/render/callback',
  path: '/api/hooks/render/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMarketsSlugRoute = ApiPublicMarketsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiPublicMarketsRoute,
} as any)
const ApiPublicPropertiesSlugRoute = ApiPublicPropertiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiPublicPropertiesRoute,
} as any)
const ApiPublicStoriesSlugRoute = ApiPublicStoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiPublicStoriesRoute,
} as any)
const ApiPublicSubjectsRequestRoute =
  ApiPublicSubjectsRequestRouteImport.update({
    id: '/api/public/subjects/request',
    path: '/api/public/subjects/request',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSubscribersConfirmRoute =
  ApiPublicSubscribersConfirmRouteImport.update({
    id: '/confirm',
    path: '/confirm',
    getParentRoute: () => ApiPublicSubscribersRoute,
  } as any)
const ApiPublicSubmissionsIdUploadsRoute =
  ApiPublicSubmissionsIdUploadsRouteImport.update({
    id: '/$id/uploads',
    path: '/$id/uploads',
    getParentRoute: () => ApiPublicSubmissionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$market': typeof SiteMarketRouteWithChildren
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/editorial-standard': typeof SiteEditorialStandardRoute
  '/exposure': typeof SiteExposureRoute
  '/faq': typeof SiteFaqRoute
  '/legal': typeof SiteLegalRoute
  '/markets': typeof SiteMarketsRouteWithChildren
  '/place-notes': typeof SitePlaceNotesRoute
  '/pricing': typeof SitePricingRoute
  '/properties': typeof SitePropertiesRoute
  '/stories': typeof SiteStoriesRouteWithChildren
  '/submit': typeof SiteSubmitRoute
  '/media/$': typeof MediaSplatRoute
  '/$market/$region': typeof SiteMarketRegionRoute
  '/$market/guide': typeof SiteMarketGuideRoute
  '/markets/$': typeof SiteMarketsSplatRoute
  '/property/$slug': typeof SitePropertySlugRoute
  '/stories/$slug': typeof SiteStoriesSlugRoute
  '/api/hooks/resend': typeof ApiHooksResendRoute
  '/api/hooks/sentry-test': typeof ApiHooksSentryTestRoute
  '/api/public/client-error': typeof ApiPublicClientErrorRoute
  '/api/public/concierge': typeof ApiPublicConciergeRoute
  '/api/public/events': typeof ApiPublicEventsRoute
  '/api/public/inquiries': typeof ApiPublicInquiriesRoute
  '/api/public/markets': typeof ApiPublicMarketsRouteWithChildren
  '/api/public/properties': typeof ApiPublicPropertiesRouteWithChildren
  '/api/public/search': typeof ApiPublicSearchRoute
  '/api/public/stories': typeof ApiPublicStoriesRouteWithChildren
  '/api/public/submissions': typeof ApiPublicSubmissionsRouteWithChildren
  '/api/public/subscribers': typeof ApiPublicSubscribersRouteWithChildren
  '/$market/': typeof SiteMarketIndexRoute
  '/markets/': typeof SiteMarketsIndexRoute
  '/stories/': typeof SiteStoriesIndexRoute
  '/archive/$kind/$slug': typeof SiteArchiveKindSlugRoute
  '/api/hooks/ops-health/$token': typeof ApiHooksOpsHealthTokenRoute
  '/api/hooks/render/callback': typeof ApiHooksRenderCallbackRoute
  '/api/public/markets/$slug': typeof ApiPublicMarketsSlugRoute
  '/api/public/properties/$slug': typeof ApiPublicPropertiesSlugRoute
  '/api/public/stories/$slug': typeof ApiPublicStoriesSlugRoute
  '/api/public/subjects/request': typeof ApiPublicSubjectsRequestRoute
  '/api/public/subscribers/confirm': typeof ApiPublicSubscribersConfirmRoute
  '/api/public/submissions/$id/uploads': typeof ApiPublicSubmissionsIdUploadsRoute
}
export interface FileRoutesByTo {
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/editorial-standard': typeof SiteEditorialStandardRoute
  '/exposure': typeof SiteExposureRoute
  '/faq': typeof SiteFaqRoute
  '/legal': typeof SiteLegalRoute
  '/place-notes': typeof SitePlaceNotesRoute
  '/pricing': typeof SitePricingRoute
  '/properties': typeof SitePropertiesRoute
  '/submit': typeof SiteSubmitRoute
  '/media/$': typeof MediaSplatRoute
  '/': typeof SiteIndexRoute
  '/$market/$region': typeof SiteMarketRegionRoute
  '/$market/guide': typeof SiteMarketGuideRoute
  '/markets/$': typeof SiteMarketsSplatRoute
  '/property/$slug': typeof SitePropertySlugRoute
  '/stories/$slug': typeof SiteStoriesSlugRoute
  '/api/hooks/resend': typeof ApiHooksResendRoute
  '/api/hooks/sentry-test': typeof ApiHooksSentryTestRoute
  '/api/public/client-error': typeof ApiPublicClientErrorRoute
  '/api/public/concierge': typeof ApiPublicConciergeRoute
  '/api/public/events': typeof ApiPublicEventsRoute
  '/api/public/inquiries': typeof ApiPublicInquiriesRoute
  '/api/public/markets': typeof ApiPublicMarketsRouteWithChildren
  '/api/public/properties': typeof ApiPublicPropertiesRouteWithChildren
  '/api/public/search': typeof ApiPublicSearchRoute
  '/api/public/stories': typeof ApiPublicStoriesRouteWithChildren
  '/api/public/submissions': typeof ApiPublicSubmissionsRouteWithChildren
  '/api/public/subscribers': typeof ApiPublicSubscribersRouteWithChildren
  '/$market': typeof SiteMarketIndexRoute
  '/markets': typeof SiteMarketsIndexRoute
  '/stories': typeof SiteStoriesIndexRoute
  '/archive/$kind/$slug': typeof SiteArchiveKindSlugRoute
  '/api/hooks/ops-health/$token': typeof ApiHooksOpsHealthTokenRoute
  '/api/hooks/render/callback': typeof ApiHooksRenderCallbackRoute
  '/api/public/markets/$slug': typeof ApiPublicMarketsSlugRoute
  '/api/public/properties/$slug': typeof ApiPublicPropertiesSlugRoute
  '/api/public/stories/$slug': typeof ApiPublicStoriesSlugRoute
  '/api/public/subjects/request': typeof ApiPublicSubjectsRequestRoute
  '/api/public/subscribers/confirm': typeof ApiPublicSubscribersConfirmRoute
  '/api/public/submissions/$id/uploads': typeof ApiPublicSubmissionsIdUploadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_site/$market': typeof SiteMarketRouteWithChildren
  '/_site/about': typeof SiteAboutRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/editorial-standard': typeof SiteEditorialStandardRoute
  '/_site/exposure': typeof SiteExposureRoute
  '/_site/faq': typeof SiteFaqRoute
  '/_site/legal': typeof SiteLegalRoute
  '/_site/markets': typeof SiteMarketsRouteWithChildren
  '/_site/place-notes': typeof SitePlaceNotesRoute
  '/_site/pricing': typeof SitePricingRoute
  '/_site/properties': typeof SitePropertiesRoute
  '/_site/stories': typeof SiteStoriesRouteWithChildren
  '/_site/submit': typeof SiteSubmitRoute
  '/media/$': typeof MediaSplatRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/$market/$region': typeof SiteMarketRegionRoute
  '/_site/$market/guide': typeof SiteMarketGuideRoute
  '/_site/markets/$': typeof SiteMarketsSplatRoute
  '/_site/property/$slug': typeof SitePropertySlugRoute
  '/_site/stories/$slug': typeof SiteStoriesSlugRoute
  '/api/hooks/resend': typeof ApiHooksResendRoute
  '/api/hooks/sentry-test': typeof ApiHooksSentryTestRoute
  '/api/public/client-error': typeof ApiPublicClientErrorRoute
  '/api/public/concierge': typeof ApiPublicConciergeRoute
  '/api/public/events': typeof ApiPublicEventsRoute
  '/api/public/inquiries': typeof ApiPublicInquiriesRoute
  '/api/public/markets': typeof ApiPublicMarketsRouteWithChildren
  '/api/public/properties': typeof ApiPublicPropertiesRouteWithChildren
  '/api/public/search': typeof ApiPublicSearchRoute
  '/api/public/stories': typeof ApiPublicStoriesRouteWithChildren
  '/api/public/submissions': typeof ApiPublicSubmissionsRouteWithChildren
  '/api/public/subscribers': typeof ApiPublicSubscribersRouteWithChildren
  '/_site/$market/': typeof SiteMarketIndexRoute
  '/_site/markets/': typeof SiteMarketsIndexRoute
  '/_site/stories/': typeof SiteStoriesIndexRoute
  '/_site/archive/$kind/$slug': typeof SiteArchiveKindSlugRoute
  '/api/hooks/ops-health/$token': typeof ApiHooksOpsHealthTokenRoute
  '/api/hooks/render/callback': typeof ApiHooksRenderCallbackRoute
  '/api/public/markets/$slug': typeof ApiPublicMarketsSlugRoute
  '/api/public/properties/$slug': typeof ApiPublicPropertiesSlugRoute
  '/api/public/stories/$slug': typeof ApiPublicStoriesSlugRoute
  '/api/public/subjects/request': typeof ApiPublicSubjectsRequestRoute
  '/api/public/subscribers/confirm': typeof ApiPublicSubscribersConfirmRoute
  '/api/public/submissions/$id/uploads': typeof ApiPublicSubmissionsIdUploadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$market'
    | '/about'
    | '/contact'
    | '/editorial-standard'
    | '/exposure'
    | '/faq'
    | '/legal'
    | '/markets'
    | '/place-notes'
    | '/pricing'
    | '/properties'
    | '/stories'
    | '/submit'
    | '/media/$'
    | '/$market/$region'
    | '/$market/guide'
    | '/markets/$'
    | '/property/$slug'
    | '/stories/$slug'
    | '/api/hooks/resend'
    | '/api/hooks/sentry-test'
    | '/api/public/client-error'
    | '/api/public/concierge'
    | '/api/public/events'
    | '/api/public/inquiries'
    | '/api/public/markets'
    | '/api/public/properties'
    | '/api/public/search'
    | '/api/public/stories'
    | '/api/public/submissions'
    | '/api/public/subscribers'
    | '/$market/'
    | '/markets/'
    | '/stories/'
    | '/archive/$kind/$slug'
    | '/api/hooks/ops-health/$token'
    | '/api/hooks/render/callback'
    | '/api/public/markets/$slug'
    | '/api/public/properties/$slug'
    | '/api/public/stories/$slug'
    | '/api/public/subjects/request'
    | '/api/public/subscribers/confirm'
    | '/api/public/submissions/$id/uploads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/robots.txt'
    | '/sitemap.xml'
    | '/about'
    | '/contact'
    | '/editorial-standard'
    | '/exposure'
    | '/faq'
    | '/legal'
    | '/place-notes'
    | '/pricing'
    | '/properties'
    | '/submit'
    | '/media/$'
    | '/'
    | '/$market/$region'
    | '/$market/guide'
    | '/markets/$'
    | '/property/$slug'
    | '/stories/$slug'
    | '/api/hooks/resend'
    | '/api/hooks/sentry-test'
    | '/api/public/client-error'
    | '/api/public/concierge'
    | '/api/public/events'
    | '/api/public/inquiries'
    | '/api/public/markets'
    | '/api/public/properties'
    | '/api/public/search'
    | '/api/public/stories'
    | '/api/public/submissions'
    | '/api/public/subscribers'
    | '/$market'
    | '/markets'
    | '/stories'
    | '/archive/$kind/$slug'
    | '/api/hooks/ops-health/$token'
    | '/api/hooks/render/callback'
    | '/api/public/markets/$slug'
    | '/api/public/properties/$slug'
    | '/api/public/stories/$slug'
    | '/api/public/subjects/request'
    | '/api/public/subscribers/confirm'
    | '/api/public/submissions/$id/uploads'
  id:
    | '__root__'
    | '/_site'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_site/$market'
    | '/_site/about'
    | '/_site/contact'
    | '/_site/editorial-standard'
    | '/_site/exposure'
    | '/_site/faq'
    | '/_site/legal'
    | '/_site/markets'
    | '/_site/place-notes'
    | '/_site/pricing'
    | '/_site/properties'
    | '/_site/stories'
    | '/_site/submit'
    | '/media/$'
    | '/_site/'
    | '/_site/$market/$region'
    | '/_site/$market/guide'
    | '/_site/markets/$'
    | '/_site/property/$slug'
    | '/_site/stories/$slug'
    | '/api/hooks/resend'
    | '/api/hooks/sentry-test'
    | '/api/public/client-error'
    | '/api/public/concierge'
    | '/api/public/events'
    | '/api/public/inquiries'
    | '/api/public/markets'
    | '/api/public/properties'
    | '/api/public/search'
    | '/api/public/stories'
    | '/api/public/submissions'
    | '/api/public/subscribers'
    | '/_site/$market/'
    | '/_site/markets/'
    | '/_site/stories/'
    | '/_site/archive/$kind/$slug'
    | '/api/hooks/ops-health/$token'
    | '/api/hooks/render/callback'
    | '/api/public/markets/$slug'
    | '/api/public/properties/$slug'
    | '/api/public/stories/$slug'
    | '/api/public/subjects/request'
    | '/api/public/subscribers/confirm'
    | '/api/public/submissions/$id/uploads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  MediaSplatRoute: typeof MediaSplatRoute
  ApiHooksResendRoute: typeof ApiHooksResendRoute
  ApiHooksSentryTestRoute: typeof ApiHooksSentryTestRoute
  ApiPublicClientErrorRoute: typeof ApiPublicClientErrorRoute
  ApiPublicConciergeRoute: typeof ApiPublicConciergeRoute
  ApiPublicEventsRoute: typeof ApiPublicEventsRoute
  ApiPublicInquiriesRoute: typeof ApiPublicInquiriesRoute
  ApiPublicMarketsRoute: typeof ApiPublicMarketsRouteWithChildren
  ApiPublicPropertiesRoute: typeof ApiPublicPropertiesRouteWithChildren
  ApiPublicSearchRoute: typeof ApiPublicSearchRoute
  ApiPublicStoriesRoute: typeof ApiPublicStoriesRouteWithChildren
  ApiPublicSubmissionsRoute: typeof ApiPublicSubmissionsRouteWithChildren
  ApiPublicSubscribersRoute: typeof ApiPublicSubscribersRouteWithChildren
  ApiHooksOpsHealthTokenRoute: typeof ApiHooksOpsHealthTokenRoute
  ApiHooksRenderCallbackRoute: typeof ApiHooksRenderCallbackRoute
  ApiPublicSubjectsRequestRoute: typeof ApiPublicSubjectsRequestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/$market': {
      id: '/_site/$market'
      path: '/$market'
      fullPath: '/$market'
      preLoaderRoute: typeof SiteMarketRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/editorial-standard': {
      id: '/_site/editorial-standard'
      path: '/editorial-standard'
      fullPath: '/editorial-standard'
      preLoaderRoute: typeof SiteEditorialStandardRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/exposure': {
      id: '/_site/exposure'
      path: '/exposure'
      fullPath: '/exposure'
      preLoaderRoute: typeof SiteExposureRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/faq': {
      id: '/_site/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof SiteFaqRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/legal': {
      id: '/_site/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof SiteLegalRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/markets': {
      id: '/_site/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof SiteMarketsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/place-notes': {
      id: '/_site/place-notes'
      path: '/place-notes'
      fullPath: '/place-notes'
      preLoaderRoute: typeof SitePlaceNotesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/pricing': {
      id: '/_site/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof SitePricingRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/properties': {
      id: '/_site/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof SitePropertiesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/stories': {
      id: '/_site/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof SiteStoriesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/submit': {
      id: '/_site/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SiteSubmitRouteImport
      parentRoute: typeof SiteRoute
    }
    '/media/$': {
      id: '/media/$'
      path: '/media/$'
      fullPath: '/media/$'
      preLoaderRoute: typeof MediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/$market/': {
      id: '/_site/$market/'
      path: '/'
      fullPath: '/$market/'
      preLoaderRoute: typeof SiteMarketIndexRouteImport
      parentRoute: typeof SiteMarketRoute
    }
    '/_site/$market/$region': {
      id: '/_site/$market/$region'
      path: '/$region'
      fullPath: '/$market/$region'
      preLoaderRoute: typeof SiteMarketRegionRouteImport
      parentRoute: typeof SiteMarketRoute
    }
    '/_site/$market/guide': {
      id: '/_site/$market/guide'
      path: '/guide'
      fullPath: '/$market/guide'
      preLoaderRoute: typeof SiteMarketGuideRouteImport
      parentRoute: typeof SiteMarketRoute
    }
    '/_site/markets/': {
      id: '/_site/markets/'
      path: '/'
      fullPath: '/markets/'
      preLoaderRoute: typeof SiteMarketsIndexRouteImport
      parentRoute: typeof SiteMarketsRoute
    }
    '/_site/markets/$': {
      id: '/_site/markets/$'
      path: '/$'
      fullPath: '/markets/$'
      preLoaderRoute: typeof SiteMarketsSplatRouteImport
      parentRoute: typeof SiteMarketsRoute
    }
    '/_site/property/$slug': {
      id: '/_site/property/$slug'
      path: '/property/$slug'
      fullPath: '/property/$slug'
      preLoaderRoute: typeof SitePropertySlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/stories/': {
      id: '/_site/stories/'
      path: '/'
      fullPath: '/stories/'
      preLoaderRoute: typeof SiteStoriesIndexRouteImport
      parentRoute: typeof SiteStoriesRoute
    }
    '/_site/stories/$slug': {
      id: '/_site/stories/$slug'
      path: '/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof SiteStoriesSlugRouteImport
      parentRoute: typeof SiteStoriesRoute
    }
    '/api/hooks/resend': {
      id: '/api/hooks/resend'
      path: '/api/hooks/resend'
      fullPath: '/api/hooks/resend'
      preLoaderRoute: typeof ApiHooksResendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hooks/sentry-test': {
      id: '/api/hooks/sentry-test'
      path: '/api/hooks/sentry-test'
      fullPath: '/api/hooks/sentry-test'
      preLoaderRoute: typeof ApiHooksSentryTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/client-error': {
      id: '/api/public/client-error'
      path: '/api/public/client-error'
      fullPath: '/api/public/client-error'
      preLoaderRoute: typeof ApiPublicClientErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/concierge': {
      id: '/api/public/concierge'
      path: '/api/public/concierge'
      fullPath: '/api/public/concierge'
      preLoaderRoute: typeof ApiPublicConciergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/events': {
      id: '/api/public/events'
      path: '/api/public/events'
      fullPath: '/api/public/events'
      preLoaderRoute: typeof ApiPublicEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/inquiries': {
      id: '/api/public/inquiries'
      path: '/api/public/inquiries'
      fullPath: '/api/public/inquiries'
      preLoaderRoute: typeof ApiPublicInquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/markets': {
      id: '/api/public/markets'
      path: '/api/public/markets'
      fullPath: '/api/public/markets'
      preLoaderRoute: typeof ApiPublicMarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/properties': {
      id: '/api/public/properties'
      path: '/api/public/properties'
      fullPath: '/api/public/properties'
      preLoaderRoute: typeof ApiPublicPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/search': {
      id: '/api/public/search'
      path: '/api/public/search'
      fullPath: '/api/public/search'
      preLoaderRoute: typeof ApiPublicSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stories': {
      id: '/api/public/stories'
      path: '/api/public/stories'
      fullPath: '/api/public/stories'
      preLoaderRoute: typeof ApiPublicStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/submissions': {
      id: '/api/public/submissions'
      path: '/api/public/submissions'
      fullPath: '/api/public/submissions'
      preLoaderRoute: typeof ApiPublicSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/subscribers': {
      id: '/api/public/subscribers'
      path: '/api/public/subscribers'
      fullPath: '/api/public/subscribers'
      preLoaderRoute: typeof ApiPublicSubscribersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/archive/$kind/$slug': {
      id: '/_site/archive/$kind/$slug'
      path: '/archive/$kind/$slug'
      fullPath: '/archive/$kind/$slug'
      preLoaderRoute: typeof SiteArchiveKindSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/api/hooks/ops-health/$token': {
      id: '/api/hooks/ops-health/$token'
      path: '/api/hooks/ops-health/$token'
      fullPath: '/api/hooks/ops-health/$token'
      preLoaderRoute: typeof ApiHooksOpsHealthTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hooks/render/callback': {
      id: '/api/hooks/render/callback'
      path: '/api/hooks/render/callback'
      fullPath: '/api/hooks/render/callback'
      preLoaderRoute: typeof ApiHooksRenderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/markets/$slug': {
      id: '/api/public/markets/$slug'
      path: '/$slug'
      fullPath: '/api/public/markets/$slug'
      preLoaderRoute: typeof ApiPublicMarketsSlugRouteImport
      parentRoute: typeof ApiPublicMarketsRoute
    }
    '/api/public/properties/$slug': {
      id: '/api/public/properties/$slug'
      path: '/$slug'
      fullPath: '/api/public/properties/$slug'
      preLoaderRoute: typeof ApiPublicPropertiesSlugRouteImport
      parentRoute: typeof ApiPublicPropertiesRoute
    }
    '/api/public/stories/$slug': {
      id: '/api/public/stories/$slug'
      path: '/$slug'
      fullPath: '/api/public/stories/$slug'
      preLoaderRoute: typeof ApiPublicStoriesSlugRouteImport
      parentRoute: typeof ApiPublicStoriesRoute
    }
    '/api/public/subjects/request': {
      id: '/api/public/subjects/request'
      path: '/api/public/subjects/request'
      fullPath: '/api/public/subjects/request'
      preLoaderRoute: typeof ApiPublicSubjectsRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/subscribers/confirm': {
      id: '/api/public/subscribers/confirm'
      path: '/confirm'
      fullPath: '/api/public/subscribers/confirm'
      preLoaderRoute: typeof ApiPublicSubscribersConfirmRouteImport
      parentRoute: typeof ApiPublicSubscribersRoute
    }
    '/api/public/submissions/$id/uploads': {
      id: '/api/public/submissions/$id/uploads'
      path: '/$id/uploads'
      fullPath: '/api/public/submissions/$id/uploads'
      preLoaderRoute: typeof ApiPublicSubmissionsIdUploadsRouteImport
      parentRoute: typeof ApiPublicSubmissionsRoute
    }
  }
}

interface SiteMarketRouteChildren {
  SiteMarketRegionRoute: typeof SiteMarketRegionRoute
  SiteMarketGuideRoute: typeof SiteMarketGuideRoute
  SiteMarketIndexRoute: typeof SiteMarketIndexRoute
}

const SiteMarketRouteChildren: SiteMarketRouteChildren = {
  SiteMarketRegionRoute: SiteMarketRegionRoute,
  SiteMarketGuideRoute: SiteMarketGuideRoute,
  SiteMarketIndexRoute: SiteMarketIndexRoute,
}

const SiteMarketRouteWithChildren = SiteMarketRoute._addFileChildren(
  SiteMarketRouteChildren,
)

interface SiteMarketsRouteChildren {
  SiteMarketsSplatRoute: typeof SiteMarketsSplatRoute
  SiteMarketsIndexRoute: typeof SiteMarketsIndexRoute
}

const SiteMarketsRouteChildren: SiteMarketsRouteChildren = {
  SiteMarketsSplatRoute: SiteMarketsSplatRoute,
  SiteMarketsIndexRoute: SiteMarketsIndexRoute,
}

const SiteMarketsRouteWithChildren = SiteMarketsRoute._addFileChildren(
  SiteMarketsRouteChildren,
)

interface SiteStoriesRouteChildren {
  SiteStoriesSlugRoute: typeof SiteStoriesSlugRoute
  SiteStoriesIndexRoute: typeof SiteStoriesIndexRoute
}

const SiteStoriesRouteChildren: SiteStoriesRouteChildren = {
  SiteStoriesSlugRoute: SiteStoriesSlugRoute,
  SiteStoriesIndexRoute: SiteStoriesIndexRoute,
}

const SiteStoriesRouteWithChildren = SiteStoriesRoute._addFileChildren(
  SiteStoriesRouteChildren,
)

interface SiteRouteChildren {
  SiteMarketRoute: typeof SiteMarketRouteWithChildren
  SiteAboutRoute: typeof SiteAboutRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteEditorialStandardRoute: typeof SiteEditorialStandardRoute
  SiteExposureRoute: typeof SiteExposureRoute
  SiteFaqRoute: typeof SiteFaqRoute
  SiteLegalRoute: typeof SiteLegalRoute
  SiteMarketsRoute: typeof SiteMarketsRouteWithChildren
  SitePlaceNotesRoute: typeof SitePlaceNotesRoute
  SitePricingRoute: typeof SitePricingRoute
  SitePropertiesRoute: typeof SitePropertiesRoute
  SiteStoriesRoute: typeof SiteStoriesRouteWithChildren
  SiteSubmitRoute: typeof SiteSubmitRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SitePropertySlugRoute: typeof SitePropertySlugRoute
  SiteArchiveKindSlugRoute: typeof SiteArchiveKindSlugRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteMarketRoute: SiteMarketRouteWithChildren,
  SiteAboutRoute: SiteAboutRoute,
  SiteContactRoute: SiteContactRoute,
  SiteEditorialStandardRoute: SiteEditorialStandardRoute,
  SiteExposureRoute: SiteExposureRoute,
  SiteFaqRoute: SiteFaqRoute,
  SiteLegalRoute: SiteLegalRoute,
  SiteMarketsRoute: SiteMarketsRouteWithChildren,
  SitePlaceNotesRoute: SitePlaceNotesRoute,
  SitePricingRoute: SitePricingRoute,
  SitePropertiesRoute: SitePropertiesRoute,
  SiteStoriesRoute: SiteStoriesRouteWithChildren,
  SiteSubmitRoute: SiteSubmitRoute,
  SiteIndexRoute: SiteIndexRoute,
  SitePropertySlugRoute: SitePropertySlugRoute,
  SiteArchiveKindSlugRoute: SiteArchiveKindSlugRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface ApiPublicMarketsRouteChildren {
  ApiPublicMarketsSlugRoute: typeof ApiPublicMarketsSlugRoute
}

const ApiPublicMarketsRouteChildren: ApiPublicMarketsRouteChildren = {
  ApiPublicMarketsSlugRoute: ApiPublicMarketsSlugRoute,
}

const ApiPublicMarketsRouteWithChildren =
  ApiPublicMarketsRoute._addFileChildren(ApiPublicMarketsRouteChildren)

interface ApiPublicPropertiesRouteChildren {
  ApiPublicPropertiesSlugRoute: typeof ApiPublicPropertiesSlugRoute
}

const ApiPublicPropertiesRouteChildren: ApiPublicPropertiesRouteChildren = {
  ApiPublicPropertiesSlugRoute: ApiPublicPropertiesSlugRoute,
}

const ApiPublicPropertiesRouteWithChildren =
  ApiPublicPropertiesRoute._addFileChildren(ApiPublicPropertiesRouteChildren)

interface ApiPublicStoriesRouteChildren {
  ApiPublicStoriesSlugRoute: typeof ApiPublicStoriesSlugRoute
}

const ApiPublicStoriesRouteChildren: ApiPublicStoriesRouteChildren = {
  ApiPublicStoriesSlugRoute: ApiPublicStoriesSlugRoute,
}

const ApiPublicStoriesRouteWithChildren =
  ApiPublicStoriesRoute._addFileChildren(ApiPublicStoriesRouteChildren)

interface ApiPublicSubmissionsRouteChildren {
  ApiPublicSubmissionsIdUploadsRoute: typeof ApiPublicSubmissionsIdUploadsRoute
}

const ApiPublicSubmissionsRouteChildren: ApiPublicSubmissionsRouteChildren = {
  ApiPublicSubmissionsIdUploadsRoute: ApiPublicSubmissionsIdUploadsRoute,
}

const ApiPublicSubmissionsRouteWithChildren =
  ApiPublicSubmissionsRoute._addFileChildren(ApiPublicSubmissionsRouteChildren)

interface ApiPublicSubscribersRouteChildren {
  ApiPublicSubscribersConfirmRoute: typeof ApiPublicSubscribersConfirmRoute
}

const ApiPublicSubscribersRouteChildren: ApiPublicSubscribersRouteChildren = {
  ApiPublicSubscribersConfirmRoute: ApiPublicSubscribersConfirmRoute,
}

const ApiPublicSubscribersRouteWithChildren =
  ApiPublicSubscribersRoute._addFileChildren(ApiPublicSubscribersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  MediaSplatRoute: MediaSplatRoute,
  ApiHooksResendRoute: ApiHooksResendRoute,
  ApiHooksSentryTestRoute: ApiHooksSentryTestRoute,
  ApiPublicClientErrorRoute: ApiPublicClientErrorRoute,
  ApiPublicConciergeRoute: ApiPublicConciergeRoute,
  ApiPublicEventsRoute: ApiPublicEventsRoute,
  ApiPublicInquiriesRoute: ApiPublicInquiriesRoute,
  ApiPublicMarketsRoute: ApiPublicMarketsRouteWithChildren,
  ApiPublicPropertiesRoute: ApiPublicPropertiesRouteWithChildren,
  ApiPublicSearchRoute: ApiPublicSearchRoute,
  ApiPublicStoriesRoute: ApiPublicStoriesRouteWithChildren,
  ApiPublicSubmissionsRoute: ApiPublicSubmissionsRouteWithChildren,
  ApiPublicSubscribersRoute: ApiPublicSubscribersRouteWithChildren,
  ApiHooksOpsHealthTokenRoute: ApiHooksOpsHealthTokenRoute,
  ApiHooksRenderCallbackRoute: ApiHooksRenderCallbackRoute,
  ApiPublicSubjectsRequestRoute: ApiPublicSubjectsRequestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
