/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketRouteImport } from './routes/$market'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EditorialStandardRouteImport } from './routes/editorial-standard'
import { Route as ExposureRouteImport } from './routes/exposure'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as PlaceNotesRouteImport } from './routes/place-notes'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as MarketIndexRouteImport } from './routes/$market.index'
import { Route as MarketRegionRouteImport } from './routes/$market.$region'
import { Route as MarketGuideRouteImport } from './routes/$market.guide'
import { Route as MarketsIndexRouteImport } from './routes/markets.index'
import { Route as MarketsSplatRouteImport } from './routes/markets.$'
import { Route as PropertySlugRouteImport } from './routes/property.$slug'
import { Route as StoriesIndexRouteImport } from './routes/stories.index'
import { Route as StoriesSlugRouteImport } from './routes/stories.$slug'
import { Route as ApiHooksSentryTestRouteImport } from './routes/api/hooks/sentry-test'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/$market',
  path: '/$market',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialStandardRoute = EditorialStandardRouteImport.update({
  id: '/editorial-standard',
  path: '/editorial-standard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExposureRoute = ExposureRouteImport.update({
  id: '/exposure',
  path: '/exposure',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaceNotesRoute = PlaceNotesRouteImport.update({
  id: '/place-notes',
  path: '/place-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketIndexRoute = MarketIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketRoute,
} as any)
const MarketRegionRoute = MarketRegionRouteImport.update({
  id: '/$region',
  path: '/$region',
  getParentRoute: () => MarketRoute,
} as any)
const MarketGuideRoute = MarketGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => MarketRoute,
} as any)
const MarketsIndexRoute = MarketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketsRoute,
} as any)
const MarketsSplatRoute = MarketsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => MarketsRoute,
} as any)
const PropertySlugRoute = PropertySlugRouteImport.update({
  id: '/property/$slug',
  path: '/property/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoriesRoute,
} as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StoriesRoute,
} as any)
const ApiHooksSentryTestRoute = ApiHooksSentryTestRouteImport.update({
  id: '/api/hooks/sentry-test',
  path: '/api/hooks/sentry-test',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$market': typeof MarketRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/editorial-standard': typeof EditorialStandardRoute
  '/exposure': typeof ExposureRoute
  '/faq': typeof FaqRoute
  '/legal': typeof LegalRoute
  '/markets': typeof MarketsRouteWithChildren
  '/place-notes': typeof PlaceNotesRoute
  '/pricing': typeof PricingRoute
  '/properties': typeof PropertiesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRouteWithChildren
  '/submit': typeof SubmitRoute
  '/$market/$region': typeof MarketRegionRoute
  '/$market/guide': typeof MarketGuideRoute
  '/markets/$': typeof MarketsSplatRoute
  '/property/$slug': typeof PropertySlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/$market/': typeof MarketIndexRoute
  '/markets/': typeof MarketsIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/api/hooks/sentry-test': typeof ApiHooksSentryTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/editorial-standard': typeof EditorialStandardRoute
  '/exposure': typeof ExposureRoute
  '/faq': typeof FaqRoute
  '/legal': typeof LegalRoute
  '/place-notes': typeof PlaceNotesRoute
  '/pricing': typeof PricingRoute
  '/properties': typeof PropertiesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/$market/$region': typeof MarketRegionRoute
  '/$market/guide': typeof MarketGuideRoute
  '/markets/$': typeof MarketsSplatRoute
  '/property/$slug': typeof PropertySlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/$market': typeof MarketIndexRoute
  '/markets': typeof MarketsIndexRoute
  '/stories': typeof StoriesIndexRoute
  '/api/hooks/sentry-test': typeof ApiHooksSentryTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$market': typeof MarketRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/editorial-standard': typeof EditorialStandardRoute
  '/exposure': typeof ExposureRoute
  '/faq': typeof FaqRoute
  '/legal': typeof LegalRoute
  '/markets': typeof MarketsRouteWithChildren
  '/place-notes': typeof PlaceNotesRoute
  '/pricing': typeof PricingRoute
  '/properties': typeof PropertiesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRouteWithChildren
  '/submit': typeof SubmitRoute
  '/$market/$region': typeof MarketRegionRoute
  '/$market/guide': typeof MarketGuideRoute
  '/markets/$': typeof MarketsSplatRoute
  '/property/$slug': typeof PropertySlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/$market/': typeof MarketIndexRoute
  '/markets/': typeof MarketsIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/api/hooks/sentry-test': typeof ApiHooksSentryTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$market'
    | '/about'
    | '/contact'
    | '/editorial-standard'
    | '/exposure'
    | '/faq'
    | '/legal'
    | '/markets'
    | '/place-notes'
    | '/pricing'
    | '/properties'
    | '/sitemap.xml'
    | '/stories'
    | '/submit'
    | '/$market/$region'
    | '/$market/guide'
    | '/markets/$'
    | '/property/$slug'
    | '/stories/$slug'
    | '/$market/'
    | '/markets/'
    | '/stories/'
    | '/api/hooks/sentry-test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/editorial-standard'
    | '/exposure'
    | '/faq'
    | '/legal'
    | '/place-notes'
    | '/pricing'
    | '/properties'
    | '/sitemap.xml'
    | '/submit'
    | '/$market/$region'
    | '/$market/guide'
    | '/markets/$'
    | '/property/$slug'
    | '/stories/$slug'
    | '/$market'
    | '/markets'
    | '/stories'
    | '/api/hooks/sentry-test'
  id:
    | '__root__'
    | '/'
    | '/$market'
    | '/about'
    | '/contact'
    | '/editorial-standard'
    | '/exposure'
    | '/faq'
    | '/legal'
    | '/markets'
    | '/place-notes'
    | '/pricing'
    | '/properties'
    | '/sitemap.xml'
    | '/stories'
    | '/submit'
    | '/$market/$region'
    | '/$market/guide'
    | '/markets/$'
    | '/property/$slug'
    | '/stories/$slug'
    | '/$market/'
    | '/markets/'
    | '/stories/'
    | '/api/hooks/sentry-test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarketRoute: typeof MarketRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EditorialStandardRoute: typeof EditorialStandardRoute
  ExposureRoute: typeof ExposureRoute
  FaqRoute: typeof FaqRoute
  LegalRoute: typeof LegalRoute
  MarketsRoute: typeof MarketsRouteWithChildren
  PlaceNotesRoute: typeof PlaceNotesRoute
  PricingRoute: typeof PricingRoute
  PropertiesRoute: typeof PropertiesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoriesRoute: typeof StoriesRouteWithChildren
  SubmitRoute: typeof SubmitRoute
  PropertySlugRoute: typeof PropertySlugRoute
  ApiHooksSentryTestRoute: typeof ApiHooksSentryTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$market': {
      id: '/$market'
      path: '/$market'
      fullPath: '/$market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-standard': {
      id: '/editorial-standard'
      path: '/editorial-standard'
      fullPath: '/editorial-standard'
      preLoaderRoute: typeof EditorialStandardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exposure': {
      id: '/exposure'
      path: '/exposure'
      fullPath: '/exposure'
      preLoaderRoute: typeof ExposureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/place-notes': {
      id: '/place-notes'
      path: '/place-notes'
      fullPath: '/place-notes'
      preLoaderRoute: typeof PlaceNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$market/': {
      id: '/$market/'
      path: '/'
      fullPath: '/$market/'
      preLoaderRoute: typeof MarketIndexRouteImport
      parentRoute: typeof MarketRoute
    }
    '/$market/$region': {
      id: '/$market/$region'
      path: '/$region'
      fullPath: '/$market/$region'
      preLoaderRoute: typeof MarketRegionRouteImport
      parentRoute: typeof MarketRoute
    }
    '/$market/guide': {
      id: '/$market/guide'
      path: '/guide'
      fullPath: '/$market/guide'
      preLoaderRoute: typeof MarketGuideRouteImport
      parentRoute: typeof MarketRoute
    }
    '/markets/': {
      id: '/markets/'
      path: '/'
      fullPath: '/markets/'
      preLoaderRoute: typeof MarketsIndexRouteImport
      parentRoute: typeof MarketsRoute
    }
    '/markets/$': {
      id: '/markets/$'
      path: '/$'
      fullPath: '/markets/$'
      preLoaderRoute: typeof MarketsSplatRouteImport
      parentRoute: typeof MarketsRoute
    }
    '/property/$slug': {
      id: '/property/$slug'
      path: '/property/$slug'
      fullPath: '/property/$slug'
      preLoaderRoute: typeof PropertySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/stories/$slug': {
      id: '/stories/$slug'
      path: '/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/api/hooks/sentry-test': {
      id: '/api/hooks/sentry-test'
      path: '/api/hooks/sentry-test'
      fullPath: '/api/hooks/sentry-test'
      preLoaderRoute: typeof ApiHooksSentryTestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MarketRouteChildren {
  MarketRegionRoute: typeof MarketRegionRoute
  MarketGuideRoute: typeof MarketGuideRoute
  MarketIndexRoute: typeof MarketIndexRoute
}

const MarketRouteChildren: MarketRouteChildren = {
  MarketRegionRoute: MarketRegionRoute,
  MarketGuideRoute: MarketGuideRoute,
  MarketIndexRoute: MarketIndexRoute,
}

const MarketRouteWithChildren =
  MarketRoute._addFileChildren(MarketRouteChildren)

interface MarketsRouteChildren {
  MarketsSplatRoute: typeof MarketsSplatRoute
  MarketsIndexRoute: typeof MarketsIndexRoute
}

const MarketsRouteChildren: MarketsRouteChildren = {
  MarketsSplatRoute: MarketsSplatRoute,
  MarketsIndexRoute: MarketsIndexRoute,
}

const MarketsRouteWithChildren =
  MarketsRoute._addFileChildren(MarketsRouteChildren)

interface StoriesRouteChildren {
  StoriesSlugRoute: typeof StoriesSlugRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
}

const StoriesRouteChildren: StoriesRouteChildren = {
  StoriesSlugRoute: StoriesSlugRoute,
  StoriesIndexRoute: StoriesIndexRoute,
}

const StoriesRouteWithChildren =
  StoriesRoute._addFileChildren(StoriesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarketRoute: MarketRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EditorialStandardRoute: EditorialStandardRoute,
  ExposureRoute: ExposureRoute,
  FaqRoute: FaqRoute,
  LegalRoute: LegalRoute,
  MarketsRoute: MarketsRouteWithChildren,
  PlaceNotesRoute: PlaceNotesRoute,
  PricingRoute: PricingRoute,
  PropertiesRoute: PropertiesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoriesRoute: StoriesRouteWithChildren,
  SubmitRoute: SubmitRoute,
  PropertySlugRoute: PropertySlugRoute,
  ApiHooksSentryTestRoute: ApiHooksSentryTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
