/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as FeedDotjsonRouteImport } from './routes/feed[.]json'
import { Route as FeedDotxmlRouteImport } from './routes/feed[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DotwellKnownChangePasswordRouteImport } from './routes/[.]well-known.change-password'
import { Route as DotwellKnownMtaStsDottxtRouteImport } from './routes/[.]well-known.mta-sts[.]txt'
import { Route as DotwellKnownSecurityDottxtRouteImport } from './routes/[.]well-known.security[.]txt'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteMarketRouteImport } from './routes/_site.$market'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteCookiesRouteImport } from './routes/_site.cookies'
import { Route as SiteEditorialStandardRouteImport } from './routes/_site.editorial-standard'
import { Route as SiteExposureRouteImport } from './routes/_site.exposure'
import { Route as SiteFaqRouteImport } from './routes/_site.faq'
import { Route as SiteLegalRouteImport } from './routes/_site.legal'
import { Route as SiteMarketsRouteImport } from './routes/_site.markets'
import { Route as SitePlaceNotesRouteImport } from './routes/_site.place-notes'
import { Route as SitePricingRouteImport } from './routes/_site.pricing'
import { Route as SitePrivacyChoicesRouteImport } from './routes/_site.privacy-choices'
import { Route as SitePropertiesRouteImport } from './routes/_site.properties'
import { Route as SiteStoriesRouteImport } from './routes/_site.stories'
import { Route as SiteSubmitRouteImport } from './routes/_site.submit'
import { Route as AdminSignInRouteImport } from './routes/admin/sign-in'
import { Route as ApiConsentRouteImport } from './routes/api/consent'
import { Route as MediaSplatRouteImport } from './routes/media.$'
import { Route as SiteMarketIndexRouteImport } from './routes/_site.$market.index'
import { Route as SiteMarketRegionRouteImport } from './routes/_site.$market.$region'
import { Route as SiteMarketGuideRouteImport } from './routes/_site.$market.guide'
import { Route as SiteMarketsIndexRouteImport } from './routes/_site.markets.index'
import { Route as SiteMarketsSplatRouteImport } from './routes/_site.markets.$'
import { Route as SitePropertySlugRouteImport } from './routes/_site.property.$slug'
import { Route as SiteStoriesIndexRouteImport } from './routes/_site.stories.index'
import { Route as SiteStoriesSlugRouteImport } from './routes/_site.stories.$slug'
import { Route as AdminAuthConfirmRouteImport } from './routes/admin/auth.confirm'
import { Route as AdminInvoicesIndexRouteImport } from './routes/admin/invoices.index'
import { Route as AdminInvoicesIdRouteImport } from './routes/admin/invoices.$id'
import { Route as AdminInvoicesNewRouteImport } from './routes/admin/invoices.new'
import { Route as AdminPeopleIndexRouteImport } from './routes/admin/people.index'
import { Route as AdminPeopleIdRouteImport } from './routes/admin/people.$id'
import { Route as AdminRequestsIndexRouteImport } from './routes/admin/requests.index'
import { Route as AdminRequestsIdRouteImport } from './routes/admin/requests.$id'
import { Route as ApiAdminMeRouteImport } from './routes/api/admin/me'
import { Route as ApiHooksResendRouteImport } from './routes/api/hooks/resend'
import { Route as ApiHooksSentryTestRouteImport } from './routes/api/hooks/sentry-test'
import { Route as ApiPublicClientErrorRouteImport } from './routes/api/public/client-error'
import { Route as ApiPublicConciergeRouteImport } from './routes/api/public/concierge'
import { Route as ApiPublicCspReportRouteImport } from './routes/api/public/csp-report'
import { Route as ApiPublicEventsRouteImport } from './routes/api/public/events'
import { Route as ApiPublicInquiriesRouteImport } from './routes/api/public/inquiries'
import { Route as ApiPublicMarketsRouteImport } from './routes/api/public/markets'
import { Route as ApiPublicPropertiesRouteImport } from './routes/api/public/properties'
import { Route as ApiPublicSearchRouteImport } from './routes/api/public/search'
import { Route as ApiPublicStoriesRouteImport } from './routes/api/public/stories'
import { Route as ApiPublicSubmissionsRouteImport } from './routes/api/public/submissions'
import { Route as ApiPublicSubscribersRouteImport } from './routes/api/public/subscribers'
import { Route as SiteArchiveKindSlugRouteImport } from './routes/_site.archive.$kind.$slug'
import { Route as ApiAdminAuthSendLinkRouteImport } from './routes/api/admin/auth.send-link'
import { Route as ApiAdminAuthSignOutRouteImport } from './routes/api/admin/auth.sign-out'
import { Route as ApiAdminAuthVerifyRouteImport } from './routes/api/admin/auth.verify'
import { Route as ApiAdminPaymentsIndexRouteImport } from './routes/api/admin/payments.index'
import { Route as ApiAdminPaymentsIdRouteImport } from './routes/api/admin/payments.$id'
import { Route as ApiAdminPaymentsIssueInvoiceRouteImport } from './routes/api/admin/payments.issue-invoice'
import { Route as ApiAdminPeopleIndexRouteImport } from './routes/api/admin/people.index'
import { Route as ApiAdminPeopleIdRouteImport } from './routes/api/admin/people.$id'
import { Route as ApiAdminSubmissionsIndexRouteImport } from './routes/api/admin/submissions.index'
import { Route as ApiAdminSubmissionsIdRouteImport } from './routes/api/admin/submissions.$id'
import { Route as ApiAdminSubmissionsStartReviewRouteImport } from './routes/api/admin/submissions.start-review'
import { Route as ApiHooksOpsHealthTokenRouteImport } from './routes/api/hooks/ops-health.$token'
import { Route as ApiHooksRenderCallbackRouteImport } from './routes/api/hooks/render.callback'
import { Route as ApiPublicMarketsSlugRouteImport } from './routes/api/public/markets.$slug'
import { Route as ApiPublicPropertiesSlugRouteImport } from './routes/api/public/properties.$slug'
import { Route as ApiPublicStoriesSlugRouteImport } from './routes/api/public/stories.$slug'
import { Route as ApiPublicSubjectsRequestRouteImport } from './routes/api/public/subjects.request'
import { Route as ApiPublicSubscribersConfirmRouteImport } from './routes/api/public/subscribers.confirm'
import { Route as ApiAdminPaymentsIdMarkPaidRouteImport } from './routes/api/admin/payments.$id.mark-paid'
import { Route as ApiAdminPaymentsIdPdfRouteImport } from './routes/api/admin/payments.$id.pdf'
import { Route as ApiAdminPaymentsIdVoidRouteImport } from './routes/api/admin/payments.$id.void'
import { Route as ApiAdminPaymentsIdWaiveRouteImport } from './routes/api/admin/payments.$id.waive'
import { Route as ApiAdminPeopleIdNotesRouteImport } from './routes/api/admin/people.$id.notes'
import { Route as ApiAdminSubmissionsIdActivateRouteImport } from './routes/api/admin/submissions.$id.activate'
import { Route as ApiAdminSubmissionsIdNoteRouteImport } from './routes/api/admin/submissions.$id.note'
import { Route as ApiAdminSubmissionsIdTimelineRouteImport } from './routes/api/admin/submissions.$id.timeline'
import { Route as ApiAdminSubmissionsIdWaiveRouteImport } from './routes/api/admin/submissions.$id.waive'
import { Route as ApiPublicSubmissionsIdUploadsRouteImport } from './routes/api/public/submissions.$id.uploads'
import { Route as ApiAdminSubmissionsIdMediaMediaIdOriginalRouteImport } from './routes/api/admin/submissions.$id.media.$mediaId.original'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedDotjsonRoute = FeedDotjsonRouteImport.update({
  id: '/feed.json',
  path: '/feed.json',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedDotxmlRoute = FeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownChangePasswordRoute =
  DotwellKnownChangePasswordRouteImport.update({
    id: '/.well-known/change-password',
    path: '/.well-known/change-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownMtaStsDottxtRoute =
  DotwellKnownMtaStsDottxtRouteImport.update({
    id: '/.well-known/mta-sts.txt',
    path: '/.well-known/mta-sts.txt',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownSecurityDottxtRoute =
  DotwellKnownSecurityDottxtRouteImport.update({
    id: '/.well-known/security.txt',
    path: '/.well-known/security.txt',
    getParentRoute: () => rootRouteImport,
  } as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteMarketRoute = SiteMarketRouteImport.update({
  id: '/$market',
  path: '/$market',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCookiesRoute = SiteCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEditorialStandardRoute = SiteEditorialStandardRouteImport.update({
  id: '/editorial-standard',
  path: '/editorial-standard',
  getParentRoute: () => SiteRoute,
} as any)
const SiteExposureRoute = SiteExposureRouteImport.update({
  id: '/exposure',
  path: '/exposure',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFaqRoute = SiteFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLegalRoute = SiteLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => SiteRoute,
} as any)
const SiteMarketsRoute = SiteMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => SiteRoute,
} as any)
const SitePlaceNotesRoute = SitePlaceNotesRouteImport.update({
  id: '/place-notes',
  path: '/place-notes',
  getParentRoute: () => SiteRoute,
} as any)
const SitePricingRoute = SitePricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => SiteRoute,
} as any)
const SitePrivacyChoicesRoute = SitePrivacyChoicesRouteImport.update({
  id: '/privacy-choices',
  path: '/privacy-choices',
  getParentRoute: () => SiteRoute,
} as any)
const SitePropertiesRoute = SitePropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => SiteRoute,
} as any)
const SiteStoriesRoute = SiteStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSubmitRoute = SiteSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => SiteRoute,
} as any)
const AdminSignInRoute = AdminSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AdminRoute,
} as any)
const ApiConsentRoute = ApiConsentRouteImport.update({
  id: '/api/consent',
  path: '/api/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaSplatRoute = MediaSplatRouteImport.update({
  id: '/media/$',
  path: '/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteMarketIndexRoute = SiteMarketIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteMarketRoute,
} as any)
const SiteMarketRegionRoute = SiteMarketRegionRouteImport.update({
  id: '/$region',
  path: '/$region',
  getParentRoute: () => SiteMarketRoute,
} as any)
const SiteMarketGuideRoute = SiteMarketGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => SiteMarketRoute,
} as any)
const SiteMarketsIndexRoute = SiteMarketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteMarketsRoute,
} as any)
const SiteMarketsSplatRoute = SiteMarketsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SiteMarketsRoute,
} as any)
const SitePropertySlugRoute = SitePropertySlugRouteImport.update({
  id: '/property/$slug',
  path: '/property/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteStoriesIndexRoute = SiteStoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteStoriesRoute,
} as any)
const SiteStoriesSlugRoute = SiteStoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SiteStoriesRoute,
} as any)
const AdminAuthConfirmRoute = AdminAuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesIndexRoute = AdminInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/invoices.index.lazy').then((d) => d.Route),
)
const AdminInvoicesIdRoute = AdminInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/invoices.$id.lazy').then((d) => d.Route),
)
const AdminInvoicesNewRoute = AdminInvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/invoices.new.lazy').then((d) => d.Route),
)
const AdminPeopleIndexRoute = AdminPeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/people.index.lazy').then((d) => d.Route),
)
const AdminPeopleIdRoute = AdminPeopleIdRouteImport.update({
  id: '/people/$id',
  path: '/people/$id',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/people.$id.lazy').then((d) => d.Route),
)
const AdminRequestsIndexRoute = AdminRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsIdRoute = AdminRequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAdminMeRoute = ApiAdminMeRouteImport.update({
  id: '/api/admin/me',
  path: '/api/admin/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHooksResendRoute = ApiHooksResendRouteImport.update({
  id: '/api/hooks/resend',
  path: '/api/hooks/resend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHooksSentryTestRoute = ApiHooksSentryTestRouteImport.update({
  id: '/api/hooks/sentry-test',
  path: '/api/hooks/sentry-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClientErrorRoute = ApiPublicClientErrorRouteImport.update({
  id: '/api/public/client-error',
  path: '/api/public/client-error',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConciergeRoute = ApiPublicConciergeRouteImport.update({
  id: '/api/public/concierge',
  path: '/api/public/concierge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCspReportRoute = ApiPublicCspReportRouteImport.update({
  id: '/api/public/csp-report',
  path: '/api/public/csp-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEventsRoute = ApiPublicEventsRouteImport.update({
  id: '/api/public/events',
  path: '/api/public/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInquiriesRoute = ApiPublicInquiriesRouteImport.update({
  id: '/api/public/inquiries',
  path: '/api/public/inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMarketsRoute = ApiPublicMarketsRouteImport.update({
  id: '/api/public/markets',
  path: '/api/public/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPropertiesRoute = ApiPublicPropertiesRouteImport.update({
  id: '/api/public/properties',
  path: '/api/public/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSearchRoute = ApiPublicSearchRouteImport.update({
  id: '/api/public/search',
  path: '/api/public/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStoriesRoute = ApiPublicStoriesRouteImport.update({
  id: '/api/public/stories',
  path: '/api/public/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSubmissionsRoute = ApiPublicSubmissionsRouteImport.update({
  id: '/api/public/submissions',
  path: '/api/public/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSubscribersRoute = ApiPublicSubscribersRouteImport.update({
  id: '/api/public/subscribers',
  path: '/api/public/subscribers',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteArchiveKindSlugRoute = SiteArchiveKindSlugRouteImport.update({
  id: '/archive/$kind/$slug',
  path: '/archive/$kind/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const ApiAdminAuthSendLinkRoute = ApiAdminAuthSendLinkRouteImport.update({
  id: '/api/admin/auth/send-link',
  path: '/api/admin/auth/send-link',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuthSignOutRoute = ApiAdminAuthSignOutRouteImport.update({
  id: '/api/admin/auth/sign-out',
  path: '/api/admin/auth/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuthVerifyRoute = ApiAdminAuthVerifyRouteImport.update({
  id: '/api/admin/auth/verify',
  path: '/api/admin/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPaymentsIndexRoute = ApiAdminPaymentsIndexRouteImport.update({
  id: '/api/admin/payments/',
  path: '/api/admin/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPaymentsIdRoute = ApiAdminPaymentsIdRouteImport.update({
  id: '/api/admin/payments/$id',
  path: '/api/admin/payments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPaymentsIssueInvoiceRoute =
  ApiAdminPaymentsIssueInvoiceRouteImport.update({
    id: '/api/admin/payments/issue-invoice',
    path: '/api/admin/payments/issue-invoice',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminPeopleIndexRoute = ApiAdminPeopleIndexRouteImport.update({
  id: '/api/admin/people/',
  path: '/api/admin/people/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPeopleIdRoute = ApiAdminPeopleIdRouteImport.update({
  id: '/api/admin/people/$id',
  path: '/api/admin/people/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSubmissionsIndexRoute =
  ApiAdminSubmissionsIndexRouteImport.update({
    id: '/api/admin/submissions/',
    path: '/api/admin/submissions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminSubmissionsIdRoute = ApiAdminSubmissionsIdRouteImport.update({
  id: '/api/admin/submissions/$id',
  path: '/api/admin/submissions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSubmissionsStartReviewRoute =
  ApiAdminSubmissionsStartReviewRouteImport.update({
    id: '/api/admin/submissions/start-review',
    path: '/api/admin/submissions/start-review',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiHooksOpsHealthTokenRoute = ApiHooksOpsHealthTokenRouteImport.update({
  id: '/api/hooks/ops-health/$token',
  path: '/api/hooks/ops-health/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHooksRenderCallbackRoute = ApiHooksRenderCallbackRouteImport.update({
  id: '/api/hooks/render/callback',
  path: '/api/hooks/render/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMarketsSlugRoute = ApiPublicMarketsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiPublicMarketsRoute,
} as any)
const ApiPublicPropertiesSlugRoute = ApiPublicPropertiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiPublicPropertiesRoute,
} as any)
const ApiPublicStoriesSlugRoute = ApiPublicStoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiPublicStoriesRoute,
} as any)
const ApiPublicSubjectsRequestRoute =
  ApiPublicSubjectsRequestRouteImport.update({
    id: '/api/public/subjects/request',
    path: '/api/public/subjects/request',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSubscribersConfirmRoute =
  ApiPublicSubscribersConfirmRouteImport.update({
    id: '/confirm',
    path: '/confirm',
    getParentRoute: () => ApiPublicSubscribersRoute,
  } as any)
const ApiAdminPaymentsIdMarkPaidRoute =
  ApiAdminPaymentsIdMarkPaidRouteImport.update({
    id: '/mark-paid',
    path: '/mark-paid',
    getParentRoute: () => ApiAdminPaymentsIdRoute,
  } as any)
const ApiAdminPaymentsIdPdfRoute = ApiAdminPaymentsIdPdfRouteImport.update({
  id: '/pdf',
  path: '/pdf',
  getParentRoute: () => ApiAdminPaymentsIdRoute,
} as any)
const ApiAdminPaymentsIdVoidRoute = ApiAdminPaymentsIdVoidRouteImport.update({
  id: '/void',
  path: '/void',
  getParentRoute: () => ApiAdminPaymentsIdRoute,
} as any)
const ApiAdminPaymentsIdWaiveRoute = ApiAdminPaymentsIdWaiveRouteImport.update({
  id: '/waive',
  path: '/waive',
  getParentRoute: () => ApiAdminPaymentsIdRoute,
} as any)
const ApiAdminPeopleIdNotesRoute = ApiAdminPeopleIdNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => ApiAdminPeopleIdRoute,
} as any)
const ApiAdminSubmissionsIdActivateRoute =
  ApiAdminSubmissionsIdActivateRouteImport.update({
    id: '/activate',
    path: '/activate',
    getParentRoute: () => ApiAdminSubmissionsIdRoute,
  } as any)
const ApiAdminSubmissionsIdNoteRoute =
  ApiAdminSubmissionsIdNoteRouteImport.update({
    id: '/note',
    path: '/note',
    getParentRoute: () => ApiAdminSubmissionsIdRoute,
  } as any)
const ApiAdminSubmissionsIdTimelineRoute =
  ApiAdminSubmissionsIdTimelineRouteImport.update({
    id: '/timeline',
    path: '/timeline',
    getParentRoute: () => ApiAdminSubmissionsIdRoute,
  } as any)
const ApiAdminSubmissionsIdWaiveRoute =
  ApiAdminSubmissionsIdWaiveRouteImport.update({
    id: '/waive',
    path: '/waive',
    getParentRoute: () => ApiAdminSubmissionsIdRoute,
  } as any)
const ApiPublicSubmissionsIdUploadsRoute =
  ApiPublicSubmissionsIdUploadsRouteImport.update({
    id: '/$id/uploads',
    path: '/$id/uploads',
    getParentRoute: () => ApiPublicSubmissionsRoute,
  } as any)
const ApiAdminSubmissionsIdMediaMediaIdOriginalRoute =
  ApiAdminSubmissionsIdMediaMediaIdOriginalRouteImport.update({
    id: '/media/$mediaId/original',
    path: '/media/$mediaId/original',
    getParentRoute: () => ApiAdminSubmissionsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/feed.json': typeof FeedDotjsonRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/change-password': typeof DotwellKnownChangePasswordRoute
  '/.well-known/mta-sts.txt': typeof DotwellKnownMtaStsDottxtRoute
  '/.well-known/security.txt': typeof DotwellKnownSecurityDottxtRoute
  '/$market': typeof SiteMarketRouteWithChildren
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/cookies': typeof SiteCookiesRoute
  '/editorial-standard': typeof SiteEditorialStandardRoute
  '/exposure': typeof SiteExposureRoute
  '/faq': typeof SiteFaqRoute
  '/legal': typeof SiteLegalRoute
  '/markets': typeof SiteMarketsRouteWithChildren
  '/place-notes': typeof SitePlaceNotesRoute
  '/pricing': typeof SitePricingRoute
  '/privacy-choices': typeof SitePrivacyChoicesRoute
  '/properties': typeof SitePropertiesRoute
  '/stories': typeof SiteStoriesRouteWithChildren
  '/submit': typeof SiteSubmitRoute
  '/admin/sign-in': typeof AdminSignInRoute
  '/api/consent': typeof ApiConsentRoute
  '/media/$': typeof MediaSplatRoute
  '/$market/$region': typeof SiteMarketRegionRoute
  '/$market/guide': typeof SiteMarketGuideRoute
  '/markets/$': typeof SiteMarketsSplatRoute
  '/property/$slug': typeof SitePropertySlugRoute
  '/stories/$slug': typeof SiteStoriesSlugRoute
  '/admin/auth/confirm': typeof AdminAuthConfirmRoute
  '/admin/invoices/$id': typeof AdminInvoicesIdRoute
  '/admin/invoices/new': typeof AdminInvoicesNewRoute
  '/admin/people/$id': typeof AdminPeopleIdRoute
  '/admin/requests/$id': typeof AdminRequestsIdRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/hooks/resend': typeof ApiHooksResendRoute
  '/api/hooks/sentry-test': typeof ApiHooksSentryTestRoute
  '/api/public/client-error': typeof ApiPublicClientErrorRoute
  '/api/public/concierge': typeof ApiPublicConciergeRoute
  '/api/public/csp-report': typeof ApiPublicCspReportRoute
  '/api/public/events': typeof ApiPublicEventsRoute
  '/api/public/inquiries': typeof ApiPublicInquiriesRoute
  '/api/public/markets': typeof ApiPublicMarketsRouteWithChildren
  '/api/public/properties': typeof ApiPublicPropertiesRouteWithChildren
  '/api/public/search': typeof ApiPublicSearchRoute
  '/api/public/stories': typeof ApiPublicStoriesRouteWithChildren
  '/api/public/submissions': typeof ApiPublicSubmissionsRouteWithChildren
  '/api/public/subscribers': typeof ApiPublicSubscribersRouteWithChildren
  '/$market/': typeof SiteMarketIndexRoute
  '/markets/': typeof SiteMarketsIndexRoute
  '/stories/': typeof SiteStoriesIndexRoute
  '/admin/invoices/': typeof AdminInvoicesIndexRoute
  '/admin/people/': typeof AdminPeopleIndexRoute
  '/admin/requests/': typeof AdminRequestsIndexRoute
  '/archive/$kind/$slug': typeof SiteArchiveKindSlugRoute
  '/api/admin/auth/send-link': typeof ApiAdminAuthSendLinkRoute
  '/api/admin/auth/sign-out': typeof ApiAdminAuthSignOutRoute
  '/api/admin/auth/verify': typeof ApiAdminAuthVerifyRoute
  '/api/admin/payments/$id': typeof ApiAdminPaymentsIdRouteWithChildren
  '/api/admin/payments/issue-invoice': typeof ApiAdminPaymentsIssueInvoiceRoute
  '/api/admin/people/$id': typeof ApiAdminPeopleIdRouteWithChildren
  '/api/admin/submissions/$id': typeof ApiAdminSubmissionsIdRouteWithChildren
  '/api/admin/submissions/start-review': typeof ApiAdminSubmissionsStartReviewRoute
  '/api/hooks/ops-health/$token': typeof ApiHooksOpsHealthTokenRoute
  '/api/hooks/render/callback': typeof ApiHooksRenderCallbackRoute
  '/api/public/markets/$slug': typeof ApiPublicMarketsSlugRoute
  '/api/public/properties/$slug': typeof ApiPublicPropertiesSlugRoute
  '/api/public/stories/$slug': typeof ApiPublicStoriesSlugRoute
  '/api/public/subjects/request': typeof ApiPublicSubjectsRequestRoute
  '/api/public/subscribers/confirm': typeof ApiPublicSubscribersConfirmRoute
  '/api/admin/payments/': typeof ApiAdminPaymentsIndexRoute
  '/api/admin/people/': typeof ApiAdminPeopleIndexRoute
  '/api/admin/submissions/': typeof ApiAdminSubmissionsIndexRoute
  '/api/admin/payments/$id/mark-paid': typeof ApiAdminPaymentsIdMarkPaidRoute
  '/api/admin/payments/$id/pdf': typeof ApiAdminPaymentsIdPdfRoute
  '/api/admin/payments/$id/void': typeof ApiAdminPaymentsIdVoidRoute
  '/api/admin/payments/$id/waive': typeof ApiAdminPaymentsIdWaiveRoute
  '/api/admin/people/$id/notes': typeof ApiAdminPeopleIdNotesRoute
  '/api/admin/submissions/$id/activate': typeof ApiAdminSubmissionsIdActivateRoute
  '/api/admin/submissions/$id/note': typeof ApiAdminSubmissionsIdNoteRoute
  '/api/admin/submissions/$id/timeline': typeof ApiAdminSubmissionsIdTimelineRoute
  '/api/admin/submissions/$id/waive': typeof ApiAdminSubmissionsIdWaiveRoute
  '/api/public/submissions/$id/uploads': typeof ApiPublicSubmissionsIdUploadsRoute
  '/api/admin/submissions/$id/media/$mediaId/original': typeof ApiAdminSubmissionsIdMediaMediaIdOriginalRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRouteWithChildren
  '/feed.json': typeof FeedDotjsonRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/change-password': typeof DotwellKnownChangePasswordRoute
  '/.well-known/mta-sts.txt': typeof DotwellKnownMtaStsDottxtRoute
  '/.well-known/security.txt': typeof DotwellKnownSecurityDottxtRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/cookies': typeof SiteCookiesRoute
  '/editorial-standard': typeof SiteEditorialStandardRoute
  '/exposure': typeof SiteExposureRoute
  '/faq': typeof SiteFaqRoute
  '/legal': typeof SiteLegalRoute
  '/place-notes': typeof SitePlaceNotesRoute
  '/pricing': typeof SitePricingRoute
  '/privacy-choices': typeof SitePrivacyChoicesRoute
  '/properties': typeof SitePropertiesRoute
  '/submit': typeof SiteSubmitRoute
  '/admin/sign-in': typeof AdminSignInRoute
  '/api/consent': typeof ApiConsentRoute
  '/media/$': typeof MediaSplatRoute
  '/': typeof SiteIndexRoute
  '/$market/$region': typeof SiteMarketRegionRoute
  '/$market/guide': typeof SiteMarketGuideRoute
  '/markets/$': typeof SiteMarketsSplatRoute
  '/property/$slug': typeof SitePropertySlugRoute
  '/stories/$slug': typeof SiteStoriesSlugRoute
  '/admin/auth/confirm': typeof AdminAuthConfirmRoute
  '/admin/invoices/$id': typeof AdminInvoicesIdRoute
  '/admin/invoices/new': typeof AdminInvoicesNewRoute
  '/admin/people/$id': typeof AdminPeopleIdRoute
  '/admin/requests/$id': typeof AdminRequestsIdRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/hooks/resend': typeof ApiHooksResendRoute
  '/api/hooks/sentry-test': typeof ApiHooksSentryTestRoute
  '/api/public/client-error': typeof ApiPublicClientErrorRoute
  '/api/public/concierge': typeof ApiPublicConciergeRoute
  '/api/public/csp-report': typeof ApiPublicCspReportRoute
  '/api/public/events': typeof ApiPublicEventsRoute
  '/api/public/inquiries': typeof ApiPublicInquiriesRoute
  '/api/public/markets': typeof ApiPublicMarketsRouteWithChildren
  '/api/public/properties': typeof ApiPublicPropertiesRouteWithChildren
  '/api/public/search': typeof ApiPublicSearchRoute
  '/api/public/stories': typeof ApiPublicStoriesRouteWithChildren
  '/api/public/submissions': typeof ApiPublicSubmissionsRouteWithChildren
  '/api/public/subscribers': typeof ApiPublicSubscribersRouteWithChildren
  '/$market': typeof SiteMarketIndexRoute
  '/markets': typeof SiteMarketsIndexRoute
  '/stories': typeof SiteStoriesIndexRoute
  '/admin/invoices': typeof AdminInvoicesIndexRoute
  '/admin/people': typeof AdminPeopleIndexRoute
  '/admin/requests': typeof AdminRequestsIndexRoute
  '/archive/$kind/$slug': typeof SiteArchiveKindSlugRoute
  '/api/admin/auth/send-link': typeof ApiAdminAuthSendLinkRoute
  '/api/admin/auth/sign-out': typeof ApiAdminAuthSignOutRoute
  '/api/admin/auth/verify': typeof ApiAdminAuthVerifyRoute
  '/api/admin/payments/$id': typeof ApiAdminPaymentsIdRouteWithChildren
  '/api/admin/payments/issue-invoice': typeof ApiAdminPaymentsIssueInvoiceRoute
  '/api/admin/people/$id': typeof ApiAdminPeopleIdRouteWithChildren
  '/api/admin/submissions/$id': typeof ApiAdminSubmissionsIdRouteWithChildren
  '/api/admin/submissions/start-review': typeof ApiAdminSubmissionsStartReviewRoute
  '/api/hooks/ops-health/$token': typeof ApiHooksOpsHealthTokenRoute
  '/api/hooks/render/callback': typeof ApiHooksRenderCallbackRoute
  '/api/public/markets/$slug': typeof ApiPublicMarketsSlugRoute
  '/api/public/properties/$slug': typeof ApiPublicPropertiesSlugRoute
  '/api/public/stories/$slug': typeof ApiPublicStoriesSlugRoute
  '/api/public/subjects/request': typeof ApiPublicSubjectsRequestRoute
  '/api/public/subscribers/confirm': typeof ApiPublicSubscribersConfirmRoute
  '/api/admin/payments': typeof ApiAdminPaymentsIndexRoute
  '/api/admin/people': typeof ApiAdminPeopleIndexRoute
  '/api/admin/submissions': typeof ApiAdminSubmissionsIndexRoute
  '/api/admin/payments/$id/mark-paid': typeof ApiAdminPaymentsIdMarkPaidRoute
  '/api/admin/payments/$id/pdf': typeof ApiAdminPaymentsIdPdfRoute
  '/api/admin/payments/$id/void': typeof ApiAdminPaymentsIdVoidRoute
  '/api/admin/payments/$id/waive': typeof ApiAdminPaymentsIdWaiveRoute
  '/api/admin/people/$id/notes': typeof ApiAdminPeopleIdNotesRoute
  '/api/admin/submissions/$id/activate': typeof ApiAdminSubmissionsIdActivateRoute
  '/api/admin/submissions/$id/note': typeof ApiAdminSubmissionsIdNoteRoute
  '/api/admin/submissions/$id/timeline': typeof ApiAdminSubmissionsIdTimelineRoute
  '/api/admin/submissions/$id/waive': typeof ApiAdminSubmissionsIdWaiveRoute
  '/api/public/submissions/$id/uploads': typeof ApiPublicSubmissionsIdUploadsRoute
  '/api/admin/submissions/$id/media/$mediaId/original': typeof ApiAdminSubmissionsIdMediaMediaIdOriginalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/feed.json': typeof FeedDotjsonRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/change-password': typeof DotwellKnownChangePasswordRoute
  '/.well-known/mta-sts.txt': typeof DotwellKnownMtaStsDottxtRoute
  '/.well-known/security.txt': typeof DotwellKnownSecurityDottxtRoute
  '/_site/$market': typeof SiteMarketRouteWithChildren
  '/_site/about': typeof SiteAboutRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/cookies': typeof SiteCookiesRoute
  '/_site/editorial-standard': typeof SiteEditorialStandardRoute
  '/_site/exposure': typeof SiteExposureRoute
  '/_site/faq': typeof SiteFaqRoute
  '/_site/legal': typeof SiteLegalRoute
  '/_site/markets': typeof SiteMarketsRouteWithChildren
  '/_site/place-notes': typeof SitePlaceNotesRoute
  '/_site/pricing': typeof SitePricingRoute
  '/_site/privacy-choices': typeof SitePrivacyChoicesRoute
  '/_site/properties': typeof SitePropertiesRoute
  '/_site/stories': typeof SiteStoriesRouteWithChildren
  '/_site/submit': typeof SiteSubmitRoute
  '/admin/sign-in': typeof AdminSignInRoute
  '/api/consent': typeof ApiConsentRoute
  '/media/$': typeof MediaSplatRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/$market/$region': typeof SiteMarketRegionRoute
  '/_site/$market/guide': typeof SiteMarketGuideRoute
  '/_site/markets/$': typeof SiteMarketsSplatRoute
  '/_site/property/$slug': typeof SitePropertySlugRoute
  '/_site/stories/$slug': typeof SiteStoriesSlugRoute
  '/admin/auth/confirm': typeof AdminAuthConfirmRoute
  '/admin/invoices/$id': typeof AdminInvoicesIdRoute
  '/admin/invoices/new': typeof AdminInvoicesNewRoute
  '/admin/people/$id': typeof AdminPeopleIdRoute
  '/admin/requests/$id': typeof AdminRequestsIdRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/hooks/resend': typeof ApiHooksResendRoute
  '/api/hooks/sentry-test': typeof ApiHooksSentryTestRoute
  '/api/public/client-error': typeof ApiPublicClientErrorRoute
  '/api/public/concierge': typeof ApiPublicConciergeRoute
  '/api/public/csp-report': typeof ApiPublicCspReportRoute
  '/api/public/events': typeof ApiPublicEventsRoute
  '/api/public/inquiries': typeof ApiPublicInquiriesRoute
  '/api/public/markets': typeof ApiPublicMarketsRouteWithChildren
  '/api/public/properties': typeof ApiPublicPropertiesRouteWithChildren
  '/api/public/search': typeof ApiPublicSearchRoute
  '/api/public/stories': typeof ApiPublicStoriesRouteWithChildren
  '/api/public/submissions': typeof ApiPublicSubmissionsRouteWithChildren
  '/api/public/subscribers': typeof ApiPublicSubscribersRouteWithChildren
  '/_site/$market/': typeof SiteMarketIndexRoute
  '/_site/markets/': typeof SiteMarketsIndexRoute
  '/_site/stories/': typeof SiteStoriesIndexRoute
  '/admin/invoices/': typeof AdminInvoicesIndexRoute
  '/admin/people/': typeof AdminPeopleIndexRoute
  '/admin/requests/': typeof AdminRequestsIndexRoute
  '/_site/archive/$kind/$slug': typeof SiteArchiveKindSlugRoute
  '/api/admin/auth/send-link': typeof ApiAdminAuthSendLinkRoute
  '/api/admin/auth/sign-out': typeof ApiAdminAuthSignOutRoute
  '/api/admin/auth/verify': typeof ApiAdminAuthVerifyRoute
  '/api/admin/payments/$id': typeof ApiAdminPaymentsIdRouteWithChildren
  '/api/admin/payments/issue-invoice': typeof ApiAdminPaymentsIssueInvoiceRoute
  '/api/admin/people/$id': typeof ApiAdminPeopleIdRouteWithChildren
  '/api/admin/submissions/$id': typeof ApiAdminSubmissionsIdRouteWithChildren
  '/api/admin/submissions/start-review': typeof ApiAdminSubmissionsStartReviewRoute
  '/api/hooks/ops-health/$token': typeof ApiHooksOpsHealthTokenRoute
  '/api/hooks/render/callback': typeof ApiHooksRenderCallbackRoute
  '/api/public/markets/$slug': typeof ApiPublicMarketsSlugRoute
  '/api/public/properties/$slug': typeof ApiPublicPropertiesSlugRoute
  '/api/public/stories/$slug': typeof ApiPublicStoriesSlugRoute
  '/api/public/subjects/request': typeof ApiPublicSubjectsRequestRoute
  '/api/public/subscribers/confirm': typeof ApiPublicSubscribersConfirmRoute
  '/api/admin/payments/': typeof ApiAdminPaymentsIndexRoute
  '/api/admin/people/': typeof ApiAdminPeopleIndexRoute
  '/api/admin/submissions/': typeof ApiAdminSubmissionsIndexRoute
  '/api/admin/payments/$id/mark-paid': typeof ApiAdminPaymentsIdMarkPaidRoute
  '/api/admin/payments/$id/pdf': typeof ApiAdminPaymentsIdPdfRoute
  '/api/admin/payments/$id/void': typeof ApiAdminPaymentsIdVoidRoute
  '/api/admin/payments/$id/waive': typeof ApiAdminPaymentsIdWaiveRoute
  '/api/admin/people/$id/notes': typeof ApiAdminPeopleIdNotesRoute
  '/api/admin/submissions/$id/activate': typeof ApiAdminSubmissionsIdActivateRoute
  '/api/admin/submissions/$id/note': typeof ApiAdminSubmissionsIdNoteRoute
  '/api/admin/submissions/$id/timeline': typeof ApiAdminSubmissionsIdTimelineRoute
  '/api/admin/submissions/$id/waive': typeof ApiAdminSubmissionsIdWaiveRoute
  '/api/public/submissions/$id/uploads': typeof ApiPublicSubmissionsIdUploadsRoute
  '/api/admin/submissions/$id/media/$mediaId/original': typeof ApiAdminSubmissionsIdMediaMediaIdOriginalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/feed.json'
    | '/feed.xml'
    | '/sitemap.xml'
    | '/.well-known/change-password'
    | '/.well-known/mta-sts.txt'
    | '/.well-known/security.txt'
    | '/$market'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/editorial-standard'
    | '/exposure'
    | '/faq'
    | '/legal'
    | '/markets'
    | '/place-notes'
    | '/pricing'
    | '/privacy-choices'
    | '/properties'
    | '/stories'
    | '/submit'
    | '/admin/sign-in'
    | '/api/consent'
    | '/media/$'
    | '/$market/$region'
    | '/$market/guide'
    | '/markets/$'
    | '/property/$slug'
    | '/stories/$slug'
    | '/admin/auth/confirm'
    | '/admin/invoices/$id'
    | '/admin/invoices/new'
    | '/admin/people/$id'
    | '/admin/requests/$id'
    | '/api/admin/me'
    | '/api/hooks/resend'
    | '/api/hooks/sentry-test'
    | '/api/public/client-error'
    | '/api/public/concierge'
    | '/api/public/csp-report'
    | '/api/public/events'
    | '/api/public/inquiries'
    | '/api/public/markets'
    | '/api/public/properties'
    | '/api/public/search'
    | '/api/public/stories'
    | '/api/public/submissions'
    | '/api/public/subscribers'
    | '/$market/'
    | '/markets/'
    | '/stories/'
    | '/admin/invoices/'
    | '/admin/people/'
    | '/admin/requests/'
    | '/archive/$kind/$slug'
    | '/api/admin/auth/send-link'
    | '/api/admin/auth/sign-out'
    | '/api/admin/auth/verify'
    | '/api/admin/payments/$id'
    | '/api/admin/payments/issue-invoice'
    | '/api/admin/people/$id'
    | '/api/admin/submissions/$id'
    | '/api/admin/submissions/start-review'
    | '/api/hooks/ops-health/$token'
    | '/api/hooks/render/callback'
    | '/api/public/markets/$slug'
    | '/api/public/properties/$slug'
    | '/api/public/stories/$slug'
    | '/api/public/subjects/request'
    | '/api/public/subscribers/confirm'
    | '/api/admin/payments/'
    | '/api/admin/people/'
    | '/api/admin/submissions/'
    | '/api/admin/payments/$id/mark-paid'
    | '/api/admin/payments/$id/pdf'
    | '/api/admin/payments/$id/void'
    | '/api/admin/payments/$id/waive'
    | '/api/admin/people/$id/notes'
    | '/api/admin/submissions/$id/activate'
    | '/api/admin/submissions/$id/note'
    | '/api/admin/submissions/$id/timeline'
    | '/api/admin/submissions/$id/waive'
    | '/api/public/submissions/$id/uploads'
    | '/api/admin/submissions/$id/media/$mediaId/original'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/feed.json'
    | '/feed.xml'
    | '/sitemap.xml'
    | '/.well-known/change-password'
    | '/.well-known/mta-sts.txt'
    | '/.well-known/security.txt'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/editorial-standard'
    | '/exposure'
    | '/faq'
    | '/legal'
    | '/place-notes'
    | '/pricing'
    | '/privacy-choices'
    | '/properties'
    | '/submit'
    | '/admin/sign-in'
    | '/api/consent'
    | '/media/$'
    | '/'
    | '/$market/$region'
    | '/$market/guide'
    | '/markets/$'
    | '/property/$slug'
    | '/stories/$slug'
    | '/admin/auth/confirm'
    | '/admin/invoices/$id'
    | '/admin/invoices/new'
    | '/admin/people/$id'
    | '/admin/requests/$id'
    | '/api/admin/me'
    | '/api/hooks/resend'
    | '/api/hooks/sentry-test'
    | '/api/public/client-error'
    | '/api/public/concierge'
    | '/api/public/csp-report'
    | '/api/public/events'
    | '/api/public/inquiries'
    | '/api/public/markets'
    | '/api/public/properties'
    | '/api/public/search'
    | '/api/public/stories'
    | '/api/public/submissions'
    | '/api/public/subscribers'
    | '/$market'
    | '/markets'
    | '/stories'
    | '/admin/invoices'
    | '/admin/people'
    | '/admin/requests'
    | '/archive/$kind/$slug'
    | '/api/admin/auth/send-link'
    | '/api/admin/auth/sign-out'
    | '/api/admin/auth/verify'
    | '/api/admin/payments/$id'
    | '/api/admin/payments/issue-invoice'
    | '/api/admin/people/$id'
    | '/api/admin/submissions/$id'
    | '/api/admin/submissions/start-review'
    | '/api/hooks/ops-health/$token'
    | '/api/hooks/render/callback'
    | '/api/public/markets/$slug'
    | '/api/public/properties/$slug'
    | '/api/public/stories/$slug'
    | '/api/public/subjects/request'
    | '/api/public/subscribers/confirm'
    | '/api/admin/payments'
    | '/api/admin/people'
    | '/api/admin/submissions'
    | '/api/admin/payments/$id/mark-paid'
    | '/api/admin/payments/$id/pdf'
    | '/api/admin/payments/$id/void'
    | '/api/admin/payments/$id/waive'
    | '/api/admin/people/$id/notes'
    | '/api/admin/submissions/$id/activate'
    | '/api/admin/submissions/$id/note'
    | '/api/admin/submissions/$id/timeline'
    | '/api/admin/submissions/$id/waive'
    | '/api/public/submissions/$id/uploads'
    | '/api/admin/submissions/$id/media/$mediaId/original'
  id:
    | '__root__'
    | '/_site'
    | '/admin'
    | '/feed.json'
    | '/feed.xml'
    | '/sitemap.xml'
    | '/.well-known/change-password'
    | '/.well-known/mta-sts.txt'
    | '/.well-known/security.txt'
    | '/_site/$market'
    | '/_site/about'
    | '/_site/contact'
    | '/_site/cookies'
    | '/_site/editorial-standard'
    | '/_site/exposure'
    | '/_site/faq'
    | '/_site/legal'
    | '/_site/markets'
    | '/_site/place-notes'
    | '/_site/pricing'
    | '/_site/privacy-choices'
    | '/_site/properties'
    | '/_site/stories'
    | '/_site/submit'
    | '/admin/sign-in'
    | '/api/consent'
    | '/media/$'
    | '/_site/'
    | '/_site/$market/$region'
    | '/_site/$market/guide'
    | '/_site/markets/$'
    | '/_site/property/$slug'
    | '/_site/stories/$slug'
    | '/admin/auth/confirm'
    | '/admin/invoices/$id'
    | '/admin/invoices/new'
    | '/admin/people/$id'
    | '/admin/requests/$id'
    | '/api/admin/me'
    | '/api/hooks/resend'
    | '/api/hooks/sentry-test'
    | '/api/public/client-error'
    | '/api/public/concierge'
    | '/api/public/csp-report'
    | '/api/public/events'
    | '/api/public/inquiries'
    | '/api/public/markets'
    | '/api/public/properties'
    | '/api/public/search'
    | '/api/public/stories'
    | '/api/public/submissions'
    | '/api/public/subscribers'
    | '/_site/$market/'
    | '/_site/markets/'
    | '/_site/stories/'
    | '/admin/invoices/'
    | '/admin/people/'
    | '/admin/requests/'
    | '/_site/archive/$kind/$slug'
    | '/api/admin/auth/send-link'
    | '/api/admin/auth/sign-out'
    | '/api/admin/auth/verify'
    | '/api/admin/payments/$id'
    | '/api/admin/payments/issue-invoice'
    | '/api/admin/people/$id'
    | '/api/admin/submissions/$id'
    | '/api/admin/submissions/start-review'
    | '/api/hooks/ops-health/$token'
    | '/api/hooks/render/callback'
    | '/api/public/markets/$slug'
    | '/api/public/properties/$slug'
    | '/api/public/stories/$slug'
    | '/api/public/subjects/request'
    | '/api/public/subscribers/confirm'
    | '/api/admin/payments/'
    | '/api/admin/people/'
    | '/api/admin/submissions/'
    | '/api/admin/payments/$id/mark-paid'
    | '/api/admin/payments/$id/pdf'
    | '/api/admin/payments/$id/void'
    | '/api/admin/payments/$id/waive'
    | '/api/admin/people/$id/notes'
    | '/api/admin/submissions/$id/activate'
    | '/api/admin/submissions/$id/note'
    | '/api/admin/submissions/$id/timeline'
    | '/api/admin/submissions/$id/waive'
    | '/api/public/submissions/$id/uploads'
    | '/api/admin/submissions/$id/media/$mediaId/original'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  FeedDotjsonRoute: typeof FeedDotjsonRoute
  FeedDotxmlRoute: typeof FeedDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DotwellKnownChangePasswordRoute: typeof DotwellKnownChangePasswordRoute
  DotwellKnownMtaStsDottxtRoute: typeof DotwellKnownMtaStsDottxtRoute
  DotwellKnownSecurityDottxtRoute: typeof DotwellKnownSecurityDottxtRoute
  ApiConsentRoute: typeof ApiConsentRoute
  MediaSplatRoute: typeof MediaSplatRoute
  ApiAdminMeRoute: typeof ApiAdminMeRoute
  ApiHooksResendRoute: typeof ApiHooksResendRoute
  ApiHooksSentryTestRoute: typeof ApiHooksSentryTestRoute
  ApiPublicClientErrorRoute: typeof ApiPublicClientErrorRoute
  ApiPublicConciergeRoute: typeof ApiPublicConciergeRoute
  ApiPublicCspReportRoute: typeof ApiPublicCspReportRoute
  ApiPublicEventsRoute: typeof ApiPublicEventsRoute
  ApiPublicInquiriesRoute: typeof ApiPublicInquiriesRoute
  ApiPublicMarketsRoute: typeof ApiPublicMarketsRouteWithChildren
  ApiPublicPropertiesRoute: typeof ApiPublicPropertiesRouteWithChildren
  ApiPublicSearchRoute: typeof ApiPublicSearchRoute
  ApiPublicStoriesRoute: typeof ApiPublicStoriesRouteWithChildren
  ApiPublicSubmissionsRoute: typeof ApiPublicSubmissionsRouteWithChildren
  ApiPublicSubscribersRoute: typeof ApiPublicSubscribersRouteWithChildren
  ApiAdminAuthSendLinkRoute: typeof ApiAdminAuthSendLinkRoute
  ApiAdminAuthSignOutRoute: typeof ApiAdminAuthSignOutRoute
  ApiAdminAuthVerifyRoute: typeof ApiAdminAuthVerifyRoute
  ApiAdminPaymentsIdRoute: typeof ApiAdminPaymentsIdRouteWithChildren
  ApiAdminPaymentsIssueInvoiceRoute: typeof ApiAdminPaymentsIssueInvoiceRoute
  ApiAdminPeopleIdRoute: typeof ApiAdminPeopleIdRouteWithChildren
  ApiAdminSubmissionsIdRoute: typeof ApiAdminSubmissionsIdRouteWithChildren
  ApiAdminSubmissionsStartReviewRoute: typeof ApiAdminSubmissionsStartReviewRoute
  ApiHooksOpsHealthTokenRoute: typeof ApiHooksOpsHealthTokenRoute
  ApiHooksRenderCallbackRoute: typeof ApiHooksRenderCallbackRoute
  ApiPublicSubjectsRequestRoute: typeof ApiPublicSubjectsRequestRoute
  ApiAdminPaymentsIndexRoute: typeof ApiAdminPaymentsIndexRoute
  ApiAdminPeopleIndexRoute: typeof ApiAdminPeopleIndexRoute
  ApiAdminSubmissionsIndexRoute: typeof ApiAdminSubmissionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed.json': {
      id: '/feed.json'
      path: '/feed.json'
      fullPath: '/feed.json'
      preLoaderRoute: typeof FeedDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed.xml': {
      id: '/feed.xml'
      path: '/feed.xml'
      fullPath: '/feed.xml'
      preLoaderRoute: typeof FeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/change-password': {
      id: '/.well-known/change-password'
      path: '/.well-known/change-password'
      fullPath: '/.well-known/change-password'
      preLoaderRoute: typeof DotwellKnownChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/mta-sts.txt': {
      id: '/.well-known/mta-sts.txt'
      path: '/.well-known/mta-sts.txt'
      fullPath: '/.well-known/mta-sts.txt'
      preLoaderRoute: typeof DotwellKnownMtaStsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/security.txt': {
      id: '/.well-known/security.txt'
      path: '/.well-known/security.txt'
      fullPath: '/.well-known/security.txt'
      preLoaderRoute: typeof DotwellKnownSecurityDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/$market': {
      id: '/_site/$market'
      path: '/$market'
      fullPath: '/$market'
      preLoaderRoute: typeof SiteMarketRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/cookies': {
      id: '/_site/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof SiteCookiesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/editorial-standard': {
      id: '/_site/editorial-standard'
      path: '/editorial-standard'
      fullPath: '/editorial-standard'
      preLoaderRoute: typeof SiteEditorialStandardRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/exposure': {
      id: '/_site/exposure'
      path: '/exposure'
      fullPath: '/exposure'
      preLoaderRoute: typeof SiteExposureRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/faq': {
      id: '/_site/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof SiteFaqRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/legal': {
      id: '/_site/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof SiteLegalRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/markets': {
      id: '/_site/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof SiteMarketsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/place-notes': {
      id: '/_site/place-notes'
      path: '/place-notes'
      fullPath: '/place-notes'
      preLoaderRoute: typeof SitePlaceNotesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/pricing': {
      id: '/_site/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof SitePricingRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/privacy-choices': {
      id: '/_site/privacy-choices'
      path: '/privacy-choices'
      fullPath: '/privacy-choices'
      preLoaderRoute: typeof SitePrivacyChoicesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/properties': {
      id: '/_site/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof SitePropertiesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/stories': {
      id: '/_site/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof SiteStoriesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/submit': {
      id: '/_site/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SiteSubmitRouteImport
      parentRoute: typeof SiteRoute
    }
    '/admin/sign-in': {
      id: '/admin/sign-in'
      path: '/sign-in'
      fullPath: '/admin/sign-in'
      preLoaderRoute: typeof AdminSignInRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/consent': {
      id: '/api/consent'
      path: '/api/consent'
      fullPath: '/api/consent'
      preLoaderRoute: typeof ApiConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$': {
      id: '/media/$'
      path: '/media/$'
      fullPath: '/media/$'
      preLoaderRoute: typeof MediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/$market/': {
      id: '/_site/$market/'
      path: '/'
      fullPath: '/$market/'
      preLoaderRoute: typeof SiteMarketIndexRouteImport
      parentRoute: typeof SiteMarketRoute
    }
    '/_site/$market/$region': {
      id: '/_site/$market/$region'
      path: '/$region'
      fullPath: '/$market/$region'
      preLoaderRoute: typeof SiteMarketRegionRouteImport
      parentRoute: typeof SiteMarketRoute
    }
    '/_site/$market/guide': {
      id: '/_site/$market/guide'
      path: '/guide'
      fullPath: '/$market/guide'
      preLoaderRoute: typeof SiteMarketGuideRouteImport
      parentRoute: typeof SiteMarketRoute
    }
    '/_site/markets/': {
      id: '/_site/markets/'
      path: '/'
      fullPath: '/markets/'
      preLoaderRoute: typeof SiteMarketsIndexRouteImport
      parentRoute: typeof SiteMarketsRoute
    }
    '/_site/markets/$': {
      id: '/_site/markets/$'
      path: '/$'
      fullPath: '/markets/$'
      preLoaderRoute: typeof SiteMarketsSplatRouteImport
      parentRoute: typeof SiteMarketsRoute
    }
    '/_site/property/$slug': {
      id: '/_site/property/$slug'
      path: '/property/$slug'
      fullPath: '/property/$slug'
      preLoaderRoute: typeof SitePropertySlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/stories/': {
      id: '/_site/stories/'
      path: '/'
      fullPath: '/stories/'
      preLoaderRoute: typeof SiteStoriesIndexRouteImport
      parentRoute: typeof SiteStoriesRoute
    }
    '/_site/stories/$slug': {
      id: '/_site/stories/$slug'
      path: '/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof SiteStoriesSlugRouteImport
      parentRoute: typeof SiteStoriesRoute
    }
    '/admin/auth/confirm': {
      id: '/admin/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/admin/auth/confirm'
      preLoaderRoute: typeof AdminAuthConfirmRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices/': {
      id: '/admin/invoices/'
      path: '/invoices'
      fullPath: '/admin/invoices/'
      preLoaderRoute: typeof AdminInvoicesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices/$id': {
      id: '/admin/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/admin/invoices/$id'
      preLoaderRoute: typeof AdminInvoicesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices/new': {
      id: '/admin/invoices/new'
      path: '/invoices/new'
      fullPath: '/admin/invoices/new'
      preLoaderRoute: typeof AdminInvoicesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/people/': {
      id: '/admin/people/'
      path: '/people'
      fullPath: '/admin/people/'
      preLoaderRoute: typeof AdminPeopleIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/people/$id': {
      id: '/admin/people/$id'
      path: '/people/$id'
      fullPath: '/admin/people/$id'
      preLoaderRoute: typeof AdminPeopleIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests/': {
      id: '/admin/requests/'
      path: '/requests'
      fullPath: '/admin/requests/'
      preLoaderRoute: typeof AdminRequestsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests/$id': {
      id: '/admin/requests/$id'
      path: '/requests/$id'
      fullPath: '/admin/requests/$id'
      preLoaderRoute: typeof AdminRequestsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/admin/me': {
      id: '/api/admin/me'
      path: '/api/admin/me'
      fullPath: '/api/admin/me'
      preLoaderRoute: typeof ApiAdminMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hooks/resend': {
      id: '/api/hooks/resend'
      path: '/api/hooks/resend'
      fullPath: '/api/hooks/resend'
      preLoaderRoute: typeof ApiHooksResendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hooks/sentry-test': {
      id: '/api/hooks/sentry-test'
      path: '/api/hooks/sentry-test'
      fullPath: '/api/hooks/sentry-test'
      preLoaderRoute: typeof ApiHooksSentryTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/client-error': {
      id: '/api/public/client-error'
      path: '/api/public/client-error'
      fullPath: '/api/public/client-error'
      preLoaderRoute: typeof ApiPublicClientErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/concierge': {
      id: '/api/public/concierge'
      path: '/api/public/concierge'
      fullPath: '/api/public/concierge'
      preLoaderRoute: typeof ApiPublicConciergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/csp-report': {
      id: '/api/public/csp-report'
      path: '/api/public/csp-report'
      fullPath: '/api/public/csp-report'
      preLoaderRoute: typeof ApiPublicCspReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/events': {
      id: '/api/public/events'
      path: '/api/public/events'
      fullPath: '/api/public/events'
      preLoaderRoute: typeof ApiPublicEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/inquiries': {
      id: '/api/public/inquiries'
      path: '/api/public/inquiries'
      fullPath: '/api/public/inquiries'
      preLoaderRoute: typeof ApiPublicInquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/markets': {
      id: '/api/public/markets'
      path: '/api/public/markets'
      fullPath: '/api/public/markets'
      preLoaderRoute: typeof ApiPublicMarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/properties': {
      id: '/api/public/properties'
      path: '/api/public/properties'
      fullPath: '/api/public/properties'
      preLoaderRoute: typeof ApiPublicPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/search': {
      id: '/api/public/search'
      path: '/api/public/search'
      fullPath: '/api/public/search'
      preLoaderRoute: typeof ApiPublicSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stories': {
      id: '/api/public/stories'
      path: '/api/public/stories'
      fullPath: '/api/public/stories'
      preLoaderRoute: typeof ApiPublicStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/submissions': {
      id: '/api/public/submissions'
      path: '/api/public/submissions'
      fullPath: '/api/public/submissions'
      preLoaderRoute: typeof ApiPublicSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/subscribers': {
      id: '/api/public/subscribers'
      path: '/api/public/subscribers'
      fullPath: '/api/public/subscribers'
      preLoaderRoute: typeof ApiPublicSubscribersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/archive/$kind/$slug': {
      id: '/_site/archive/$kind/$slug'
      path: '/archive/$kind/$slug'
      fullPath: '/archive/$kind/$slug'
      preLoaderRoute: typeof SiteArchiveKindSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/api/admin/auth/send-link': {
      id: '/api/admin/auth/send-link'
      path: '/api/admin/auth/send-link'
      fullPath: '/api/admin/auth/send-link'
      preLoaderRoute: typeof ApiAdminAuthSendLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/auth/sign-out': {
      id: '/api/admin/auth/sign-out'
      path: '/api/admin/auth/sign-out'
      fullPath: '/api/admin/auth/sign-out'
      preLoaderRoute: typeof ApiAdminAuthSignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/auth/verify': {
      id: '/api/admin/auth/verify'
      path: '/api/admin/auth/verify'
      fullPath: '/api/admin/auth/verify'
      preLoaderRoute: typeof ApiAdminAuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/payments/': {
      id: '/api/admin/payments/'
      path: '/api/admin/payments'
      fullPath: '/api/admin/payments/'
      preLoaderRoute: typeof ApiAdminPaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/payments/$id': {
      id: '/api/admin/payments/$id'
      path: '/api/admin/payments/$id'
      fullPath: '/api/admin/payments/$id'
      preLoaderRoute: typeof ApiAdminPaymentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/payments/issue-invoice': {
      id: '/api/admin/payments/issue-invoice'
      path: '/api/admin/payments/issue-invoice'
      fullPath: '/api/admin/payments/issue-invoice'
      preLoaderRoute: typeof ApiAdminPaymentsIssueInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/people/': {
      id: '/api/admin/people/'
      path: '/api/admin/people'
      fullPath: '/api/admin/people/'
      preLoaderRoute: typeof ApiAdminPeopleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/people/$id': {
      id: '/api/admin/people/$id'
      path: '/api/admin/people/$id'
      fullPath: '/api/admin/people/$id'
      preLoaderRoute: typeof ApiAdminPeopleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/submissions/': {
      id: '/api/admin/submissions/'
      path: '/api/admin/submissions'
      fullPath: '/api/admin/submissions/'
      preLoaderRoute: typeof ApiAdminSubmissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/submissions/$id': {
      id: '/api/admin/submissions/$id'
      path: '/api/admin/submissions/$id'
      fullPath: '/api/admin/submissions/$id'
      preLoaderRoute: typeof ApiAdminSubmissionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/submissions/start-review': {
      id: '/api/admin/submissions/start-review'
      path: '/api/admin/submissions/start-review'
      fullPath: '/api/admin/submissions/start-review'
      preLoaderRoute: typeof ApiAdminSubmissionsStartReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hooks/ops-health/$token': {
      id: '/api/hooks/ops-health/$token'
      path: '/api/hooks/ops-health/$token'
      fullPath: '/api/hooks/ops-health/$token'
      preLoaderRoute: typeof ApiHooksOpsHealthTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hooks/render/callback': {
      id: '/api/hooks/render/callback'
      path: '/api/hooks/render/callback'
      fullPath: '/api/hooks/render/callback'
      preLoaderRoute: typeof ApiHooksRenderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/markets/$slug': {
      id: '/api/public/markets/$slug'
      path: '/$slug'
      fullPath: '/api/public/markets/$slug'
      preLoaderRoute: typeof ApiPublicMarketsSlugRouteImport
      parentRoute: typeof ApiPublicMarketsRoute
    }
    '/api/public/properties/$slug': {
      id: '/api/public/properties/$slug'
      path: '/$slug'
      fullPath: '/api/public/properties/$slug'
      preLoaderRoute: typeof ApiPublicPropertiesSlugRouteImport
      parentRoute: typeof ApiPublicPropertiesRoute
    }
    '/api/public/stories/$slug': {
      id: '/api/public/stories/$slug'
      path: '/$slug'
      fullPath: '/api/public/stories/$slug'
      preLoaderRoute: typeof ApiPublicStoriesSlugRouteImport
      parentRoute: typeof ApiPublicStoriesRoute
    }
    '/api/public/subjects/request': {
      id: '/api/public/subjects/request'
      path: '/api/public/subjects/request'
      fullPath: '/api/public/subjects/request'
      preLoaderRoute: typeof ApiPublicSubjectsRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/subscribers/confirm': {
      id: '/api/public/subscribers/confirm'
      path: '/confirm'
      fullPath: '/api/public/subscribers/confirm'
      preLoaderRoute: typeof ApiPublicSubscribersConfirmRouteImport
      parentRoute: typeof ApiPublicSubscribersRoute
    }
    '/api/admin/payments/$id/mark-paid': {
      id: '/api/admin/payments/$id/mark-paid'
      path: '/mark-paid'
      fullPath: '/api/admin/payments/$id/mark-paid'
      preLoaderRoute: typeof ApiAdminPaymentsIdMarkPaidRouteImport
      parentRoute: typeof ApiAdminPaymentsIdRoute
    }
    '/api/admin/payments/$id/pdf': {
      id: '/api/admin/payments/$id/pdf'
      path: '/pdf'
      fullPath: '/api/admin/payments/$id/pdf'
      preLoaderRoute: typeof ApiAdminPaymentsIdPdfRouteImport
      parentRoute: typeof ApiAdminPaymentsIdRoute
    }
    '/api/admin/payments/$id/void': {
      id: '/api/admin/payments/$id/void'
      path: '/void'
      fullPath: '/api/admin/payments/$id/void'
      preLoaderRoute: typeof ApiAdminPaymentsIdVoidRouteImport
      parentRoute: typeof ApiAdminPaymentsIdRoute
    }
    '/api/admin/payments/$id/waive': {
      id: '/api/admin/payments/$id/waive'
      path: '/waive'
      fullPath: '/api/admin/payments/$id/waive'
      preLoaderRoute: typeof ApiAdminPaymentsIdWaiveRouteImport
      parentRoute: typeof ApiAdminPaymentsIdRoute
    }
    '/api/admin/people/$id/notes': {
      id: '/api/admin/people/$id/notes'
      path: '/notes'
      fullPath: '/api/admin/people/$id/notes'
      preLoaderRoute: typeof ApiAdminPeopleIdNotesRouteImport
      parentRoute: typeof ApiAdminPeopleIdRoute
    }
    '/api/admin/submissions/$id/activate': {
      id: '/api/admin/submissions/$id/activate'
      path: '/activate'
      fullPath: '/api/admin/submissions/$id/activate'
      preLoaderRoute: typeof ApiAdminSubmissionsIdActivateRouteImport
      parentRoute: typeof ApiAdminSubmissionsIdRoute
    }
    '/api/admin/submissions/$id/note': {
      id: '/api/admin/submissions/$id/note'
      path: '/note'
      fullPath: '/api/admin/submissions/$id/note'
      preLoaderRoute: typeof ApiAdminSubmissionsIdNoteRouteImport
      parentRoute: typeof ApiAdminSubmissionsIdRoute
    }
    '/api/admin/submissions/$id/timeline': {
      id: '/api/admin/submissions/$id/timeline'
      path: '/timeline'
      fullPath: '/api/admin/submissions/$id/timeline'
      preLoaderRoute: typeof ApiAdminSubmissionsIdTimelineRouteImport
      parentRoute: typeof ApiAdminSubmissionsIdRoute
    }
    '/api/admin/submissions/$id/waive': {
      id: '/api/admin/submissions/$id/waive'
      path: '/waive'
      fullPath: '/api/admin/submissions/$id/waive'
      preLoaderRoute: typeof ApiAdminSubmissionsIdWaiveRouteImport
      parentRoute: typeof ApiAdminSubmissionsIdRoute
    }
    '/api/public/submissions/$id/uploads': {
      id: '/api/public/submissions/$id/uploads'
      path: '/$id/uploads'
      fullPath: '/api/public/submissions/$id/uploads'
      preLoaderRoute: typeof ApiPublicSubmissionsIdUploadsRouteImport
      parentRoute: typeof ApiPublicSubmissionsRoute
    }
    '/api/admin/submissions/$id/media/$mediaId/original': {
      id: '/api/admin/submissions/$id/media/$mediaId/original'
      path: '/media/$mediaId/original'
      fullPath: '/api/admin/submissions/$id/media/$mediaId/original'
      preLoaderRoute: typeof ApiAdminSubmissionsIdMediaMediaIdOriginalRouteImport
      parentRoute: typeof ApiAdminSubmissionsIdRoute
    }
  }
}

interface SiteMarketRouteChildren {
  SiteMarketRegionRoute: typeof SiteMarketRegionRoute
  SiteMarketGuideRoute: typeof SiteMarketGuideRoute
  SiteMarketIndexRoute: typeof SiteMarketIndexRoute
}

const SiteMarketRouteChildren: SiteMarketRouteChildren = {
  SiteMarketRegionRoute: SiteMarketRegionRoute,
  SiteMarketGuideRoute: SiteMarketGuideRoute,
  SiteMarketIndexRoute: SiteMarketIndexRoute,
}

const SiteMarketRouteWithChildren = SiteMarketRoute._addFileChildren(
  SiteMarketRouteChildren,
)

interface SiteMarketsRouteChildren {
  SiteMarketsSplatRoute: typeof SiteMarketsSplatRoute
  SiteMarketsIndexRoute: typeof SiteMarketsIndexRoute
}

const SiteMarketsRouteChildren: SiteMarketsRouteChildren = {
  SiteMarketsSplatRoute: SiteMarketsSplatRoute,
  SiteMarketsIndexRoute: SiteMarketsIndexRoute,
}

const SiteMarketsRouteWithChildren = SiteMarketsRoute._addFileChildren(
  SiteMarketsRouteChildren,
)

interface SiteStoriesRouteChildren {
  SiteStoriesSlugRoute: typeof SiteStoriesSlugRoute
  SiteStoriesIndexRoute: typeof SiteStoriesIndexRoute
}

const SiteStoriesRouteChildren: SiteStoriesRouteChildren = {
  SiteStoriesSlugRoute: SiteStoriesSlugRoute,
  SiteStoriesIndexRoute: SiteStoriesIndexRoute,
}

const SiteStoriesRouteWithChildren = SiteStoriesRoute._addFileChildren(
  SiteStoriesRouteChildren,
)

interface SiteRouteChildren {
  SiteMarketRoute: typeof SiteMarketRouteWithChildren
  SiteAboutRoute: typeof SiteAboutRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteCookiesRoute: typeof SiteCookiesRoute
  SiteEditorialStandardRoute: typeof SiteEditorialStandardRoute
  SiteExposureRoute: typeof SiteExposureRoute
  SiteFaqRoute: typeof SiteFaqRoute
  SiteLegalRoute: typeof SiteLegalRoute
  SiteMarketsRoute: typeof SiteMarketsRouteWithChildren
  SitePlaceNotesRoute: typeof SitePlaceNotesRoute
  SitePricingRoute: typeof SitePricingRoute
  SitePrivacyChoicesRoute: typeof SitePrivacyChoicesRoute
  SitePropertiesRoute: typeof SitePropertiesRoute
  SiteStoriesRoute: typeof SiteStoriesRouteWithChildren
  SiteSubmitRoute: typeof SiteSubmitRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SitePropertySlugRoute: typeof SitePropertySlugRoute
  SiteArchiveKindSlugRoute: typeof SiteArchiveKindSlugRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteMarketRoute: SiteMarketRouteWithChildren,
  SiteAboutRoute: SiteAboutRoute,
  SiteContactRoute: SiteContactRoute,
  SiteCookiesRoute: SiteCookiesRoute,
  SiteEditorialStandardRoute: SiteEditorialStandardRoute,
  SiteExposureRoute: SiteExposureRoute,
  SiteFaqRoute: SiteFaqRoute,
  SiteLegalRoute: SiteLegalRoute,
  SiteMarketsRoute: SiteMarketsRouteWithChildren,
  SitePlaceNotesRoute: SitePlaceNotesRoute,
  SitePricingRoute: SitePricingRoute,
  SitePrivacyChoicesRoute: SitePrivacyChoicesRoute,
  SitePropertiesRoute: SitePropertiesRoute,
  SiteStoriesRoute: SiteStoriesRouteWithChildren,
  SiteSubmitRoute: SiteSubmitRoute,
  SiteIndexRoute: SiteIndexRoute,
  SitePropertySlugRoute: SitePropertySlugRoute,
  SiteArchiveKindSlugRoute: SiteArchiveKindSlugRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AdminRouteChildren {
  AdminSignInRoute: typeof AdminSignInRoute
  AdminAuthConfirmRoute: typeof AdminAuthConfirmRoute
  AdminInvoicesIdRoute: typeof AdminInvoicesIdRoute
  AdminInvoicesNewRoute: typeof AdminInvoicesNewRoute
  AdminPeopleIdRoute: typeof AdminPeopleIdRoute
  AdminRequestsIdRoute: typeof AdminRequestsIdRoute
  AdminInvoicesIndexRoute: typeof AdminInvoicesIndexRoute
  AdminPeopleIndexRoute: typeof AdminPeopleIndexRoute
  AdminRequestsIndexRoute: typeof AdminRequestsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSignInRoute: AdminSignInRoute,
  AdminAuthConfirmRoute: AdminAuthConfirmRoute,
  AdminInvoicesIdRoute: AdminInvoicesIdRoute,
  AdminInvoicesNewRoute: AdminInvoicesNewRoute,
  AdminPeopleIdRoute: AdminPeopleIdRoute,
  AdminRequestsIdRoute: AdminRequestsIdRoute,
  AdminInvoicesIndexRoute: AdminInvoicesIndexRoute,
  AdminPeopleIndexRoute: AdminPeopleIndexRoute,
  AdminRequestsIndexRoute: AdminRequestsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApiPublicMarketsRouteChildren {
  ApiPublicMarketsSlugRoute: typeof ApiPublicMarketsSlugRoute
}

const ApiPublicMarketsRouteChildren: ApiPublicMarketsRouteChildren = {
  ApiPublicMarketsSlugRoute: ApiPublicMarketsSlugRoute,
}

const ApiPublicMarketsRouteWithChildren =
  ApiPublicMarketsRoute._addFileChildren(ApiPublicMarketsRouteChildren)

interface ApiPublicPropertiesRouteChildren {
  ApiPublicPropertiesSlugRoute: typeof ApiPublicPropertiesSlugRoute
}

const ApiPublicPropertiesRouteChildren: ApiPublicPropertiesRouteChildren = {
  ApiPublicPropertiesSlugRoute: ApiPublicPropertiesSlugRoute,
}

const ApiPublicPropertiesRouteWithChildren =
  ApiPublicPropertiesRoute._addFileChildren(ApiPublicPropertiesRouteChildren)

interface ApiPublicStoriesRouteChildren {
  ApiPublicStoriesSlugRoute: typeof ApiPublicStoriesSlugRoute
}

const ApiPublicStoriesRouteChildren: ApiPublicStoriesRouteChildren = {
  ApiPublicStoriesSlugRoute: ApiPublicStoriesSlugRoute,
}

const ApiPublicStoriesRouteWithChildren =
  ApiPublicStoriesRoute._addFileChildren(ApiPublicStoriesRouteChildren)

interface ApiPublicSubmissionsRouteChildren {
  ApiPublicSubmissionsIdUploadsRoute: typeof ApiPublicSubmissionsIdUploadsRoute
}

const ApiPublicSubmissionsRouteChildren: ApiPublicSubmissionsRouteChildren = {
  ApiPublicSubmissionsIdUploadsRoute: ApiPublicSubmissionsIdUploadsRoute,
}

const ApiPublicSubmissionsRouteWithChildren =
  ApiPublicSubmissionsRoute._addFileChildren(ApiPublicSubmissionsRouteChildren)

interface ApiPublicSubscribersRouteChildren {
  ApiPublicSubscribersConfirmRoute: typeof ApiPublicSubscribersConfirmRoute
}

const ApiPublicSubscribersRouteChildren: ApiPublicSubscribersRouteChildren = {
  ApiPublicSubscribersConfirmRoute: ApiPublicSubscribersConfirmRoute,
}

const ApiPublicSubscribersRouteWithChildren =
  ApiPublicSubscribersRoute._addFileChildren(ApiPublicSubscribersRouteChildren)

interface ApiAdminPaymentsIdRouteChildren {
  ApiAdminPaymentsIdMarkPaidRoute: typeof ApiAdminPaymentsIdMarkPaidRoute
  ApiAdminPaymentsIdPdfRoute: typeof ApiAdminPaymentsIdPdfRoute
  ApiAdminPaymentsIdVoidRoute: typeof ApiAdminPaymentsIdVoidRoute
  ApiAdminPaymentsIdWaiveRoute: typeof ApiAdminPaymentsIdWaiveRoute
}

const ApiAdminPaymentsIdRouteChildren: ApiAdminPaymentsIdRouteChildren = {
  ApiAdminPaymentsIdMarkPaidRoute: ApiAdminPaymentsIdMarkPaidRoute,
  ApiAdminPaymentsIdPdfRoute: ApiAdminPaymentsIdPdfRoute,
  ApiAdminPaymentsIdVoidRoute: ApiAdminPaymentsIdVoidRoute,
  ApiAdminPaymentsIdWaiveRoute: ApiAdminPaymentsIdWaiveRoute,
}

const ApiAdminPaymentsIdRouteWithChildren =
  ApiAdminPaymentsIdRoute._addFileChildren(ApiAdminPaymentsIdRouteChildren)

interface ApiAdminPeopleIdRouteChildren {
  ApiAdminPeopleIdNotesRoute: typeof ApiAdminPeopleIdNotesRoute
}

const ApiAdminPeopleIdRouteChildren: ApiAdminPeopleIdRouteChildren = {
  ApiAdminPeopleIdNotesRoute: ApiAdminPeopleIdNotesRoute,
}

const ApiAdminPeopleIdRouteWithChildren =
  ApiAdminPeopleIdRoute._addFileChildren(ApiAdminPeopleIdRouteChildren)

interface ApiAdminSubmissionsIdRouteChildren {
  ApiAdminSubmissionsIdActivateRoute: typeof ApiAdminSubmissionsIdActivateRoute
  ApiAdminSubmissionsIdNoteRoute: typeof ApiAdminSubmissionsIdNoteRoute
  ApiAdminSubmissionsIdTimelineRoute: typeof ApiAdminSubmissionsIdTimelineRoute
  ApiAdminSubmissionsIdWaiveRoute: typeof ApiAdminSubmissionsIdWaiveRoute
  ApiAdminSubmissionsIdMediaMediaIdOriginalRoute: typeof ApiAdminSubmissionsIdMediaMediaIdOriginalRoute
}

const ApiAdminSubmissionsIdRouteChildren: ApiAdminSubmissionsIdRouteChildren = {
  ApiAdminSubmissionsIdActivateRoute: ApiAdminSubmissionsIdActivateRoute,
  ApiAdminSubmissionsIdNoteRoute: ApiAdminSubmissionsIdNoteRoute,
  ApiAdminSubmissionsIdTimelineRoute: ApiAdminSubmissionsIdTimelineRoute,
  ApiAdminSubmissionsIdWaiveRoute: ApiAdminSubmissionsIdWaiveRoute,
  ApiAdminSubmissionsIdMediaMediaIdOriginalRoute:
    ApiAdminSubmissionsIdMediaMediaIdOriginalRoute,
}

const ApiAdminSubmissionsIdRouteWithChildren =
  ApiAdminSubmissionsIdRoute._addFileChildren(
    ApiAdminSubmissionsIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  FeedDotjsonRoute: FeedDotjsonRoute,
  FeedDotxmlRoute: FeedDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DotwellKnownChangePasswordRoute: DotwellKnownChangePasswordRoute,
  DotwellKnownMtaStsDottxtRoute: DotwellKnownMtaStsDottxtRoute,
  DotwellKnownSecurityDottxtRoute: DotwellKnownSecurityDottxtRoute,
  ApiConsentRoute: ApiConsentRoute,
  MediaSplatRoute: MediaSplatRoute,
  ApiAdminMeRoute: ApiAdminMeRoute,
  ApiHooksResendRoute: ApiHooksResendRoute,
  ApiHooksSentryTestRoute: ApiHooksSentryTestRoute,
  ApiPublicClientErrorRoute: ApiPublicClientErrorRoute,
  ApiPublicConciergeRoute: ApiPublicConciergeRoute,
  ApiPublicCspReportRoute: ApiPublicCspReportRoute,
  ApiPublicEventsRoute: ApiPublicEventsRoute,
  ApiPublicInquiriesRoute: ApiPublicInquiriesRoute,
  ApiPublicMarketsRoute: ApiPublicMarketsRouteWithChildren,
  ApiPublicPropertiesRoute: ApiPublicPropertiesRouteWithChildren,
  ApiPublicSearchRoute: ApiPublicSearchRoute,
  ApiPublicStoriesRoute: ApiPublicStoriesRouteWithChildren,
  ApiPublicSubmissionsRoute: ApiPublicSubmissionsRouteWithChildren,
  ApiPublicSubscribersRoute: ApiPublicSubscribersRouteWithChildren,
  ApiAdminAuthSendLinkRoute: ApiAdminAuthSendLinkRoute,
  ApiAdminAuthSignOutRoute: ApiAdminAuthSignOutRoute,
  ApiAdminAuthVerifyRoute: ApiAdminAuthVerifyRoute,
  ApiAdminPaymentsIdRoute: ApiAdminPaymentsIdRouteWithChildren,
  ApiAdminPaymentsIssueInvoiceRoute: ApiAdminPaymentsIssueInvoiceRoute,
  ApiAdminPeopleIdRoute: ApiAdminPeopleIdRouteWithChildren,
  ApiAdminSubmissionsIdRoute: ApiAdminSubmissionsIdRouteWithChildren,
  ApiAdminSubmissionsStartReviewRoute: ApiAdminSubmissionsStartReviewRoute,
  ApiHooksOpsHealthTokenRoute: ApiHooksOpsHealthTokenRoute,
  ApiHooksRenderCallbackRoute: ApiHooksRenderCallbackRoute,
  ApiPublicSubjectsRequestRoute: ApiPublicSubjectsRequestRoute,
  ApiAdminPaymentsIndexRoute: ApiAdminPaymentsIndexRoute,
  ApiAdminPeopleIndexRoute: ApiAdminPeopleIndexRoute,
  ApiAdminSubmissionsIndexRoute: ApiAdminSubmissionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
