// Generated by `bun run gen:types` from the public schema. Do not edit by hand.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.18"
  }
  public: {
    Tables: {
      agent_keys: {
        Row: {
          created_at: string
          id: string
          key_hash: string
          label: string
          last_used_at: string | null
          revoked_at: string | null
          scopes: string[]
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          key_hash: string
          label: string
          last_used_at?: string | null
          revoked_at?: string | null
          scopes?: string[]
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          key_hash?: string
          label?: string
          last_used_at?: string | null
          revoked_at?: string | null
          scopes?: string[]
          user_id?: string
        }
        Relationships: []
      }
      analytics_events: {
        Row: {
          data: Json
          event: string
          id: number
          occurred_at: string
          path: string
          received_at: string
        }
        Insert: {
          data?: Json
          event: string
          id?: never
          occurred_at: string
          path: string
          received_at?: string
        }
        Update: {
          data?: Json
          event?: string
          id?: never
          occurred_at?: string
          path?: string
          received_at?: string
        }
        Relationships: []
      }
      analytics_events_default: {
        Row: {
          data: Json
          event: string
          id: number
          occurred_at: string
          path: string
          received_at: string
        }
        Insert: {
          data?: Json
          event: string
          id?: never
          occurred_at: string
          path: string
          received_at?: string
        }
        Update: {
          data?: Json
          event?: string
          id?: never
          occurred_at?: string
          path?: string
          received_at?: string
        }
        Relationships: []
      }
      analytics_events_y2026m10: {
        Row: {
          data: Json
          event: string
          id: number
          occurred_at: string
          path: string
          received_at: string
        }
        Insert: {
          data?: Json
          event: string
          id?: never
          occurred_at: string
          path: string
          received_at?: string
        }
        Update: {
          data?: Json
          event?: string
          id?: never
          occurred_at?: string
          path?: string
          received_at?: string
        }
        Relationships: []
      }
      analytics_events_y2026m11: {
        Row: {
          data: Json
          event: string
          id: number
          occurred_at: string
          path: string
          received_at: string
        }
        Insert: {
          data?: Json
          event: string
          id?: never
          occurred_at: string
          path: string
          received_at?: string
        }
        Update: {
          data?: Json
          event?: string
          id?: never
          occurred_at?: string
          path?: string
          received_at?: string
        }
        Relationships: []
      }
      analytics_events_y2026m12: {
        Row: {
          data: Json
          event: string
          id: number
          occurred_at: string
          path: string
          received_at: string
        }
        Insert: {
          data?: Json
          event: string
          id?: never
          occurred_at: string
          path: string
          received_at?: string
        }
        Update: {
          data?: Json
          event?: string
          id?: never
          occurred_at?: string
          path?: string
          received_at?: string
        }
        Relationships: []
      }
      audit_log: {
        Row: {
          action: string
          actor_id: string | null
          actor_kind: Database["public"]["Enums"]["actor_kind"] | null
          after: Json | null
          at: string
          before: Json | null
          entity: string
          entity_id: string | null
          id: number
          note: string | null
          request_id: string | null
        }
        Insert: {
          action: string
          actor_id?: string | null
          actor_kind?: Database["public"]["Enums"]["actor_kind"] | null
          after?: Json | null
          at?: string
          before?: Json | null
          entity: string
          entity_id?: string | null
          id?: never
          note?: string | null
          request_id?: string | null
        }
        Update: {
          action?: string
          actor_id?: string | null
          actor_kind?: Database["public"]["Enums"]["actor_kind"] | null
          after?: Json | null
          at?: string
          before?: Json | null
          entity?: string
          entity_id?: string | null
          id?: never
          note?: string | null
          request_id?: string | null
        }
        Relationships: []
      }
      campaign_reports: {
        Row: {
          campaign_id: string
          channel_mix: Json
          clicks: number
          created_at: string
          ctr: number | null
          geography: Json
          id: string
          impressions: number
          media_spend: number
          owned_distribution: Json
          period_end: string
          period_start: string
          reach: number
          top_creative: string | null
          updated_at: string
          video_views: number | null
        }
        Insert: {
          campaign_id: string
          channel_mix?: Json
          clicks?: number
          created_at?: string
          ctr?: number | null
          geography?: Json
          id?: string
          impressions?: number
          media_spend?: number
          owned_distribution?: Json
          period_end: string
          period_start: string
          reach?: number
          top_creative?: string | null
          updated_at?: string
          video_views?: number | null
        }
        Update: {
          campaign_id?: string
          channel_mix?: Json
          clicks?: number
          created_at?: string
          ctr?: number | null
          geography?: Json
          id?: string
          impressions?: number
          media_spend?: number
          owned_distribution?: Json
          period_end?: string
          period_start?: string
          reach?: number
          top_creative?: string | null
          updated_at?: string
          video_views?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "campaign_reports_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "campaigns"
            referencedColumns: ["id"]
          },
        ]
      }
      campaigns: {
        Row: {
          created_at: string
          ends_on: string | null
          featured_status: Database["public"]["Enums"]["channel_status"]
          homepage_status: Database["public"]["Enums"]["channel_status"]
          id: string
          management_fee: number | null
          media_budget: number
          newsletter_status: Database["public"]["Enums"]["channel_status"]
          package: Database["public"]["Enums"]["exposure_package"]
          payment_id: string
          programmatic_status: Database["public"]["Enums"]["channel_status"]
          property_id: string
          social_status: Database["public"]["Enums"]["channel_status"]
          starts_on: string | null
          submission_id: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          ends_on?: string | null
          featured_status?: Database["public"]["Enums"]["channel_status"]
          homepage_status?: Database["public"]["Enums"]["channel_status"]
          id?: string
          management_fee?: number | null
          media_budget?: number
          newsletter_status?: Database["public"]["Enums"]["channel_status"]
          package: Database["public"]["Enums"]["exposure_package"]
          payment_id: string
          programmatic_status?: Database["public"]["Enums"]["channel_status"]
          property_id: string
          social_status?: Database["public"]["Enums"]["channel_status"]
          starts_on?: string | null
          submission_id?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          ends_on?: string | null
          featured_status?: Database["public"]["Enums"]["channel_status"]
          homepage_status?: Database["public"]["Enums"]["channel_status"]
          id?: string
          management_fee?: number | null
          media_budget?: number
          newsletter_status?: Database["public"]["Enums"]["channel_status"]
          package?: Database["public"]["Enums"]["exposure_package"]
          payment_id?: string
          programmatic_status?: Database["public"]["Enums"]["channel_status"]
          property_id?: string
          social_status?: Database["public"]["Enums"]["channel_status"]
          starts_on?: string | null
          submission_id?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "campaigns_payment_id_fkey"
            columns: ["payment_id"]
            isOneToOne: true
            referencedRelation: "payments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "campaigns_property_id_fkey"
            columns: ["property_id"]
            isOneToOne: false
            referencedRelation: "properties"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "campaigns_submission_id_fkey"
            columns: ["submission_id"]
            isOneToOne: false
            referencedRelation: "submissions"
            referencedColumns: ["id"]
          },
        ]
      }
      contacts: {
        Row: {
          archived_at: string | null
          brokerage: string | null
          created_at: string
          email: string
          id: string
          kind: Database["public"]["Enums"]["submitter_kind"]
          name: string
          notes: string | null
          phone: string | null
          updated_at: string
        }
        Insert: {
          archived_at?: string | null
          brokerage?: string | null
          created_at?: string
          email: string
          id?: string
          kind: Database["public"]["Enums"]["submitter_kind"]
          name: string
          notes?: string | null
          phone?: string | null
          updated_at?: string
        }
        Update: {
          archived_at?: string | null
          brokerage?: string | null
          created_at?: string
          email?: string
          id?: string
          kind?: Database["public"]["Enums"]["submitter_kind"]
          name?: string
          notes?: string | null
          phone?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      decline_reasons: {
        Row: {
          code: string
          email_paragraph: string
          enabled: boolean
          id: string
          label: string
          sort: number
        }
        Insert: {
          code: string
          email_paragraph: string
          enabled?: boolean
          id?: string
          label: string
          sort?: number
        }
        Update: {
          code?: string
          email_paragraph?: string
          enabled?: boolean
          id?: string
          label?: string
          sort?: number
        }
        Relationships: []
      }
      inquiries: {
        Row: {
          assigned_to: string | null
          details: Json
          email: string
          forwarded_at: string | null
          forwarded_payload: Json | null
          id: string
          intent: Database["public"]["Enums"]["inquiry_intent"]
          ip_hash: string | null
          location: string | null
          message: string
          name: string
          phone: string | null
          received_at: string
          source_path: string
          state: Database["public"]["Enums"]["inquiry_state"]
          subject_kind: string | null
          subject_slug: string | null
          subject_title: string | null
          topic: string | null
          turnstile_ok: boolean
        }
        Insert: {
          assigned_to?: string | null
          details?: Json
          email: string
          forwarded_at?: string | null
          forwarded_payload?: Json | null
          id?: string
          intent: Database["public"]["Enums"]["inquiry_intent"]
          ip_hash?: string | null
          location?: string | null
          message: string
          name: string
          phone?: string | null
          received_at?: string
          source_path: string
          state?: Database["public"]["Enums"]["inquiry_state"]
          subject_kind?: string | null
          subject_slug?: string | null
          subject_title?: string | null
          topic?: string | null
          turnstile_ok?: boolean
        }
        Update: {
          assigned_to?: string | null
          details?: Json
          email?: string
          forwarded_at?: string | null
          forwarded_payload?: Json | null
          id?: string
          intent?: Database["public"]["Enums"]["inquiry_intent"]
          ip_hash?: string | null
          location?: string | null
          message?: string
          name?: string
          phone?: string | null
          received_at?: string
          source_path?: string
          state?: Database["public"]["Enums"]["inquiry_state"]
          subject_kind?: string | null
          subject_slug?: string | null
          subject_title?: string | null
          topic?: string | null
          turnstile_ok?: boolean
        }
        Relationships: []
      }
      market_guide_entries: {
        Row: {
          created_at: string
          id: string
          label: string
          market_slug: string
          region_slug: string | null
          section: string
          sort_order: number
          text: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          label: string
          market_slug: string
          region_slug?: string | null
          section: string
          sort_order?: number
          text: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          label?: string
          market_slug?: string
          region_slug?: string | null
          section?: string
          sort_order?: number
          text?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "market_guide_entries_market_slug_fkey"
            columns: ["market_slug"]
            isOneToOne: false
            referencedRelation: "markets"
            referencedColumns: ["slug"]
          },
          {
            foreignKeyName: "market_guide_entries_region_slug_fkey"
            columns: ["region_slug"]
            isOneToOne: false
            referencedRelation: "regions"
            referencedColumns: ["slug"]
          },
        ]
      }
      market_notes: {
        Row: {
          created_at: string
          id: string
          label: string
          market_slug: string
          sort_order: number
          text: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          label: string
          market_slug: string
          sort_order?: number
          text: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          label?: string
          market_slug?: string
          sort_order?: number
          text?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "market_notes_market_slug_fkey"
            columns: ["market_slug"]
            isOneToOne: false
            referencedRelation: "markets"
            referencedColumns: ["slug"]
          },
        ]
      }
      markets: {
        Row: {
          coming_soon: boolean
          country: string
          created_at: string
          currency: string
          image: string | null
          image_variants: Json
          interest_copy: string | null
          intro: string
          name: string
          places: string[]
          slug: string
          sort_order: number
          updated_at: string
        }
        Insert: {
          coming_soon?: boolean
          country: string
          created_at?: string
          currency?: string
          image?: string | null
          image_variants?: Json
          interest_copy?: string | null
          intro: string
          name: string
          places?: string[]
          slug: string
          sort_order?: number
          updated_at?: string
        }
        Update: {
          coming_soon?: boolean
          country?: string
          created_at?: string
          currency?: string
          image?: string | null
          image_variants?: Json
          interest_copy?: string | null
          intro?: string
          name?: string
          places?: string[]
          slug?: string
          sort_order?: number
          updated_at?: string
        }
        Relationships: []
      }
      migration_checksums: {
        Row: {
          pushed_at: string
          sha256: string
          version: string
        }
        Insert: {
          pushed_at?: string
          sha256: string
          version: string
        }
        Update: {
          pushed_at?: string
          sha256?: string
          version?: string
        }
        Relationships: []
      }
      payments: {
        Row: {
          amount: number
          created_at: string
          currency: string
          id: string
          invoice_file_key: string | null
          invoice_number: string | null
          issued_at: string | null
          issued_by: string | null
          method: Database["public"]["Enums"]["payment_method"]
          notes: string | null
          paid_at: string | null
          paid_marked_by: string | null
          preferred_method: string | null
          product: Database["public"]["Enums"]["exposure_package"]
          property_id: string | null
          status: Database["public"]["Enums"]["payment_status"]
          stripe_payment_intent: string | null
          submission_id: string
          updated_at: string
        }
        Insert: {
          amount: number
          created_at?: string
          currency?: string
          id?: string
          invoice_file_key?: string | null
          invoice_number?: string | null
          issued_at?: string | null
          issued_by?: string | null
          method?: Database["public"]["Enums"]["payment_method"]
          notes?: string | null
          paid_at?: string | null
          paid_marked_by?: string | null
          preferred_method?: string | null
          product: Database["public"]["Enums"]["exposure_package"]
          property_id?: string | null
          status?: Database["public"]["Enums"]["payment_status"]
          stripe_payment_intent?: string | null
          submission_id: string
          updated_at?: string
        }
        Update: {
          amount?: number
          created_at?: string
          currency?: string
          id?: string
          invoice_file_key?: string | null
          invoice_number?: string | null
          issued_at?: string | null
          issued_by?: string | null
          method?: Database["public"]["Enums"]["payment_method"]
          notes?: string | null
          paid_at?: string | null
          paid_marked_by?: string | null
          preferred_method?: string | null
          product?: Database["public"]["Enums"]["exposure_package"]
          property_id?: string | null
          status?: Database["public"]["Enums"]["payment_status"]
          stripe_payment_intent?: string | null
          submission_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "payments_property_id_fkey"
            columns: ["property_id"]
            isOneToOne: false
            referencedRelation: "properties"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "payments_submission_id_fkey"
            columns: ["submission_id"]
            isOneToOne: false
            referencedRelation: "submissions"
            referencedColumns: ["id"]
          },
        ]
      }
      pii_columns: {
        Row: {
          column_name: string
          table_name: string
        }
        Insert: {
          column_name: string
          table_name: string
        }
        Update: {
          column_name?: string
          table_name?: string
        }
        Relationships: []
      }
      properties: {
        Row: {
          address: string
          architect: string | null
          archived_at: string | null
          baths: number | null
          beds: number | null
          campaign_tier: Database["public"]["Enums"]["campaign_tier"]
          city: string
          coordinates: unknown
          country: string | null
          created_at: string
          created_by: string | null
          currency: string
          designer: string | null
          editorial_state: Database["public"]["Enums"]["editorial_state"]
          featured_rank: number | null
          first_published_at: string | null
          hero_image: string | null
          hero_rank: number | null
          id: string
          interior_sq_ft: number | null
          listing_url: string | null
          lot_acres: number | null
          market_slug: string
          neighborhood: string | null
          og_image_key: string | null
          place: string | null
          presented_by_owner: boolean
          preview_nonce: string
          price: number | null
          published_at: string | null
          region_slug: string | null
          representative_id: string | null
          search_text: unknown
          slug: string
          source: Database["public"]["Enums"]["submission_source"]
          state: string
          status: Database["public"]["Enums"]["listing_status"]
          story: string[]
          style: string | null
          submission_id: string | null
          taken_down_at: string | null
          title: string
          type: Database["public"]["Enums"]["property_type"]
          unpublish_reason: string | null
          unpublished_at: string | null
          updated_at: string
          updated_by: string | null
          version: number
          video: Json | null
          year_built: number | null
        }
        Insert: {
          address: string
          architect?: string | null
          archived_at?: string | null
          baths?: number | null
          beds?: number | null
          campaign_tier?: Database["public"]["Enums"]["campaign_tier"]
          city: string
          coordinates?: unknown
          country?: string | null
          created_at?: string
          created_by?: string | null
          currency?: string
          designer?: string | null
          editorial_state?: Database["public"]["Enums"]["editorial_state"]
          featured_rank?: number | null
          first_published_at?: string | null
          hero_image?: string | null
          hero_rank?: number | null
          id?: string
          interior_sq_ft?: number | null
          listing_url?: string | null
          lot_acres?: number | null
          market_slug: string
          neighborhood?: string | null
          og_image_key?: string | null
          place?: string | null
          presented_by_owner?: boolean
          preview_nonce?: string
          price?: number | null
          published_at?: string | null
          region_slug?: string | null
          representative_id?: string | null
          search_text?: unknown
          slug: string
          source?: Database["public"]["Enums"]["submission_source"]
          state: string
          status?: Database["public"]["Enums"]["listing_status"]
          story?: string[]
          style?: string | null
          submission_id?: string | null
          taken_down_at?: string | null
          title: string
          type: Database["public"]["Enums"]["property_type"]
          unpublish_reason?: string | null
          unpublished_at?: string | null
          updated_at?: string
          updated_by?: string | null
          version?: number
          video?: Json | null
          year_built?: number | null
        }
        Update: {
          address?: string
          architect?: string | null
          archived_at?: string | null
          baths?: number | null
          beds?: number | null
          campaign_tier?: Database["public"]["Enums"]["campaign_tier"]
          city?: string
          coordinates?: unknown
          country?: string | null
          created_at?: string
          created_by?: string | null
          currency?: string
          designer?: string | null
          editorial_state?: Database["public"]["Enums"]["editorial_state"]
          featured_rank?: number | null
          first_published_at?: string | null
          hero_image?: string | null
          hero_rank?: number | null
          id?: string
          interior_sq_ft?: number | null
          listing_url?: string | null
          lot_acres?: number | null
          market_slug?: string
          neighborhood?: string | null
          og_image_key?: string | null
          place?: string | null
          presented_by_owner?: boolean
          preview_nonce?: string
          price?: number | null
          published_at?: string | null
          region_slug?: string | null
          representative_id?: string | null
          search_text?: unknown
          slug?: string
          source?: Database["public"]["Enums"]["submission_source"]
          state?: string
          status?: Database["public"]["Enums"]["listing_status"]
          story?: string[]
          style?: string | null
          submission_id?: string | null
          taken_down_at?: string | null
          title?: string
          type?: Database["public"]["Enums"]["property_type"]
          unpublish_reason?: string | null
          unpublished_at?: string | null
          updated_at?: string
          updated_by?: string | null
          version?: number
          video?: Json | null
          year_built?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "properties_market_slug_fkey"
            columns: ["market_slug"]
            isOneToOne: false
            referencedRelation: "markets"
            referencedColumns: ["slug"]
          },
          {
            foreignKeyName: "properties_region_market_fkey"
            columns: ["region_slug", "market_slug"]
            isOneToOne: false
            referencedRelation: "regions"
            referencedColumns: ["slug", "market_slug"]
          },
          {
            foreignKeyName: "properties_representative_id_fkey"
            columns: ["representative_id"]
            isOneToOne: false
            referencedRelation: "representatives"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "properties_submission_fk"
            columns: ["submission_id"]
            isOneToOne: false
            referencedRelation: "submissions"
            referencedColumns: ["id"]
          },
        ]
      }
      property_features: {
        Row: {
          created_at: string
          feature: string
          property_id: string
          sort_order: number
          updated_at: string
        }
        Insert: {
          created_at?: string
          feature: string
          property_id: string
          sort_order?: number
          updated_at?: string
        }
        Update: {
          created_at?: string
          feature?: string
          property_id?: string
          sort_order?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "property_features_property_id_fkey"
            columns: ["property_id"]
            isOneToOne: false
            referencedRelation: "properties"
            referencedColumns: ["id"]
          },
        ]
      }
      property_media: {
        Row: {
          alt: string | null
          created_at: string
          id: string
          media_key: string | null
          orientation: Database["public"]["Enums"]["media_orientation"] | null
          property_id: string
          render_job_id: string | null
          sort_order: number
          staging_path: string | null
          updated_at: string
          variants: Json
        }
        Insert: {
          alt?: string | null
          created_at?: string
          id?: string
          media_key?: string | null
          orientation?: Database["public"]["Enums"]["media_orientation"] | null
          property_id: string
          render_job_id?: string | null
          sort_order?: number
          staging_path?: string | null
          updated_at?: string
          variants?: Json
        }
        Update: {
          alt?: string | null
          created_at?: string
          id?: string
          media_key?: string | null
          orientation?: Database["public"]["Enums"]["media_orientation"] | null
          property_id?: string
          render_job_id?: string | null
          sort_order?: number
          staging_path?: string | null
          updated_at?: string
          variants?: Json
        }
        Relationships: [
          {
            foreignKeyName: "property_media_property_id_fkey"
            columns: ["property_id"]
            isOneToOne: false
            referencedRelation: "properties"
            referencedColumns: ["id"]
          },
        ]
      }
      property_related: {
        Row: {
          created_at: string
          property_id: string
          related_slug: string
          sort_order: number
          updated_at: string
        }
        Insert: {
          created_at?: string
          property_id: string
          related_slug: string
          sort_order?: number
          updated_at?: string
        }
        Update: {
          created_at?: string
          property_id?: string
          related_slug?: string
          sort_order?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "property_related_property_id_fkey"
            columns: ["property_id"]
            isOneToOne: false
            referencedRelation: "properties"
            referencedColumns: ["id"]
          },
        ]
      }
      redirects: {
        Row: {
          archived_at: string | null
          created_at: string
          created_by: string | null
          enabled: boolean
          from_path: string
          id: string
          note: string | null
          status: number
          to_path: string
          updated_at: string
        }
        Insert: {
          archived_at?: string | null
          created_at?: string
          created_by?: string | null
          enabled?: boolean
          from_path: string
          id?: string
          note?: string | null
          status?: number
          to_path: string
          updated_at?: string
        }
        Update: {
          archived_at?: string | null
          created_at?: string
          created_by?: string | null
          enabled?: boolean
          from_path?: string
          id?: string
          note?: string | null
          status?: number
          to_path?: string
          updated_at?: string
        }
        Relationships: []
      }
      regions: {
        Row: {
          created_at: string
          image: string | null
          image_variants: Json
          intro: string
          market_slug: string
          name: string
          places: string[]
          slug: string
          sort_order: number
          updated_at: string
        }
        Insert: {
          created_at?: string
          image?: string | null
          image_variants?: Json
          intro: string
          market_slug: string
          name: string
          places?: string[]
          slug: string
          sort_order?: number
          updated_at?: string
        }
        Update: {
          created_at?: string
          image?: string | null
          image_variants?: Json
          intro?: string
          market_slug?: string
          name?: string
          places?: string[]
          slug?: string
          sort_order?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "regions_market_slug_fkey"
            columns: ["market_slug"]
            isOneToOne: false
            referencedRelation: "markets"
            referencedColumns: ["slug"]
          },
        ]
      }
      representatives: {
        Row: {
          brokerage: string
          created_at: string
          email: string | null
          id: string
          license: string | null
          name: string
          phone: string | null
          photo: string | null
          updated_at: string
        }
        Insert: {
          brokerage: string
          created_at?: string
          email?: string | null
          id?: string
          license?: string | null
          name: string
          phone?: string | null
          photo?: string | null
          updated_at?: string
        }
        Update: {
          brokerage?: string
          created_at?: string
          email?: string | null
          id?: string
          license?: string | null
          name?: string
          phone?: string | null
          photo?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      retention_policies: {
        Row: {
          action: string
          enabled: boolean
          keep_for: string | null
          key: string
          note: string | null
          table_name: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          action: string
          enabled?: boolean
          keep_for?: string | null
          key: string
          note?: string | null
          table_name: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          action?: string
          enabled?: boolean
          keep_for?: string | null
          key?: string
          note?: string | null
          table_name?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      settings: {
        Row: {
          key: string
          updated_at: string
          updated_by: string | null
          value: Json
        }
        Insert: {
          key: string
          updated_at?: string
          updated_by?: string | null
          value: Json
        }
        Update: {
          key?: string
          updated_at?: string
          updated_by?: string | null
          value?: Json
        }
        Relationships: []
      }
      slug_history: {
        Row: {
          changed_at: string
          property_id: string
          slug: string
        }
        Insert: {
          changed_at?: string
          property_id: string
          slug: string
        }
        Update: {
          changed_at?: string
          property_id?: string
          slug?: string
        }
        Relationships: [
          {
            foreignKeyName: "slug_history_property_id_fkey"
            columns: ["property_id"]
            isOneToOne: false
            referencedRelation: "properties"
            referencedColumns: ["id"]
          },
        ]
      }
      stories: {
        Row: {
          archived_at: string | null
          author_id: string | null
          body: string[]
          category: Database["public"]["Enums"]["story_category"]
          created_at: string
          deck: string
          editorial_state: Database["public"]["Enums"]["editorial_state"]
          id: string
          image: string | null
          image_variants: Json
          market_slug: string
          properties: string[]
          published_at: string | null
          slug: string
          title: string
          updated_at: string
        }
        Insert: {
          archived_at?: string | null
          author_id?: string | null
          body?: string[]
          category: Database["public"]["Enums"]["story_category"]
          created_at?: string
          deck: string
          editorial_state?: Database["public"]["Enums"]["editorial_state"]
          id?: string
          image?: string | null
          image_variants?: Json
          market_slug: string
          properties?: string[]
          published_at?: string | null
          slug: string
          title: string
          updated_at?: string
        }
        Update: {
          archived_at?: string | null
          author_id?: string | null
          body?: string[]
          category?: Database["public"]["Enums"]["story_category"]
          created_at?: string
          deck?: string
          editorial_state?: Database["public"]["Enums"]["editorial_state"]
          id?: string
          image?: string | null
          image_variants?: Json
          market_slug?: string
          properties?: string[]
          published_at?: string | null
          slug?: string
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "stories_market_slug_fkey"
            columns: ["market_slug"]
            isOneToOne: false
            referencedRelation: "markets"
            referencedColumns: ["slug"]
          },
        ]
      }
      submission_media: {
        Row: {
          bytes: number | null
          id: string
          mime: string | null
          name: string
          sha256: string | null
          storage_path: string
          submission_id: string
          uploaded_at: string | null
        }
        Insert: {
          bytes?: number | null
          id?: string
          mime?: string | null
          name: string
          sha256?: string | null
          storage_path: string
          submission_id: string
          uploaded_at?: string | null
        }
        Update: {
          bytes?: number | null
          id?: string
          mime?: string | null
          name?: string
          sha256?: string | null
          storage_path?: string
          submission_id?: string
          uploaded_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "submission_media_submission_id_fkey"
            columns: ["submission_id"]
            isOneToOne: false
            referencedRelation: "submissions"
            referencedColumns: ["id"]
          },
        ]
      }
      submissions: {
        Row: {
          accepted_at: string | null
          accepted_by: string | null
          activated_at: string | null
          activated_by: string | null
          address: string
          architect: string | null
          baths: number | null
          beds: number | null
          brokerage: string | null
          city: string
          contact_id: string | null
          currency: string
          decline_note: string | null
          decline_reason_id: string | null
          designer: string | null
          id: string
          interior_sq_ft: number | null
          ip_hash: string | null
          listed_with_agent: boolean | null
          listing_agent_brokerage: string | null
          listing_agent_name: string | null
          listing_url: string | null
          media_budget: number | null
          notes: Json[]
          package: Database["public"]["Enums"]["exposure_package"]
          photography_url: string | null
          price: number | null
          property_id: string | null
          property_type: Database["public"]["Enums"]["property_type"]
          received_at: string
          reviewed_at: string | null
          reviewed_by: string | null
          rights_confirmed_at: string
          rights_ip_hash: string
          rights_version: string
          significance: string
          source_path: string
          source_url: string | null
          state: Database["public"]["Enums"]["accepted_state"]
          story: string
          submitter_email: string
          submitter_kind: Database["public"]["Enums"]["submitter_kind"]
          submitter_name: string
          submitter_phone: string | null
          turnstile_ok: boolean
          video_url: string | null
          workflow_state: Database["public"]["Enums"]["submission_state"]
          year_built: number | null
          year_renovated: number | null
          zip: string
        }
        Insert: {
          accepted_at?: string | null
          accepted_by?: string | null
          activated_at?: string | null
          activated_by?: string | null
          address: string
          architect?: string | null
          baths?: number | null
          beds?: number | null
          brokerage?: string | null
          city: string
          contact_id?: string | null
          currency?: string
          decline_note?: string | null
          decline_reason_id?: string | null
          designer?: string | null
          id?: string
          interior_sq_ft?: number | null
          ip_hash?: string | null
          listed_with_agent?: boolean | null
          listing_agent_brokerage?: string | null
          listing_agent_name?: string | null
          listing_url?: string | null
          media_budget?: number | null
          notes?: Json[]
          package: Database["public"]["Enums"]["exposure_package"]
          photography_url?: string | null
          price?: number | null
          property_id?: string | null
          property_type: Database["public"]["Enums"]["property_type"]
          received_at?: string
          reviewed_at?: string | null
          reviewed_by?: string | null
          rights_confirmed_at: string
          rights_ip_hash: string
          rights_version: string
          significance: string
          source_path: string
          source_url?: string | null
          state: Database["public"]["Enums"]["accepted_state"]
          story: string
          submitter_email: string
          submitter_kind: Database["public"]["Enums"]["submitter_kind"]
          submitter_name: string
          submitter_phone?: string | null
          turnstile_ok?: boolean
          video_url?: string | null
          workflow_state?: Database["public"]["Enums"]["submission_state"]
          year_built?: number | null
          year_renovated?: number | null
          zip: string
        }
        Update: {
          accepted_at?: string | null
          accepted_by?: string | null
          activated_at?: string | null
          activated_by?: string | null
          address?: string
          architect?: string | null
          baths?: number | null
          beds?: number | null
          brokerage?: string | null
          city?: string
          contact_id?: string | null
          currency?: string
          decline_note?: string | null
          decline_reason_id?: string | null
          designer?: string | null
          id?: string
          interior_sq_ft?: number | null
          ip_hash?: string | null
          listed_with_agent?: boolean | null
          listing_agent_brokerage?: string | null
          listing_agent_name?: string | null
          listing_url?: string | null
          media_budget?: number | null
          notes?: Json[]
          package?: Database["public"]["Enums"]["exposure_package"]
          photography_url?: string | null
          price?: number | null
          property_id?: string | null
          property_type?: Database["public"]["Enums"]["property_type"]
          received_at?: string
          reviewed_at?: string | null
          reviewed_by?: string | null
          rights_confirmed_at?: string
          rights_ip_hash?: string
          rights_version?: string
          significance?: string
          source_path?: string
          source_url?: string | null
          state?: Database["public"]["Enums"]["accepted_state"]
          story?: string
          submitter_email?: string
          submitter_kind?: Database["public"]["Enums"]["submitter_kind"]
          submitter_name?: string
          submitter_phone?: string | null
          turnstile_ok?: boolean
          video_url?: string | null
          workflow_state?: Database["public"]["Enums"]["submission_state"]
          year_built?: number | null
          year_renovated?: number | null
          zip?: string
        }
        Relationships: [
          {
            foreignKeyName: "submissions_contact_id_fkey"
            columns: ["contact_id"]
            isOneToOne: false
            referencedRelation: "contacts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "submissions_decline_reason_id_fkey"
            columns: ["decline_reason_id"]
            isOneToOne: false
            referencedRelation: "decline_reasons"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "submissions_property_id_fkey"
            columns: ["property_id"]
            isOneToOne: false
            referencedRelation: "properties"
            referencedColumns: ["id"]
          },
        ]
      }
      subscribers: {
        Row: {
          archived_at: string | null
          confirm_token_hash: string | null
          confirmed_at: string | null
          created_at: string
          email: string
          id: string
          markets: string[]
          resend_contact_id: string | null
          source: string
          unsubscribed_at: string | null
          updated_at: string
        }
        Insert: {
          archived_at?: string | null
          confirm_token_hash?: string | null
          confirmed_at?: string | null
          created_at?: string
          email: string
          id?: string
          markets?: string[]
          resend_contact_id?: string | null
          source: string
          unsubscribed_at?: string | null
          updated_at?: string
        }
        Update: {
          archived_at?: string | null
          confirm_token_hash?: string | null
          confirmed_at?: string | null
          created_at?: string
          email?: string
          id?: string
          markets?: string[]
          resend_contact_id?: string | null
          source?: string
          unsubscribed_at?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      user_roles: {
        Row: {
          actor_kind: Database["public"]["Enums"]["actor_kind"]
          created_at: string
          disabled_at: string | null
          display_name: string | null
          id: string
          role: Database["public"]["Enums"]["app_role"]
          updated_at: string
          user_id: string
        }
        Insert: {
          actor_kind?: Database["public"]["Enums"]["actor_kind"]
          created_at?: string
          disabled_at?: string | null
          display_name?: string | null
          id?: string
          role: Database["public"]["Enums"]["app_role"]
          updated_at?: string
          user_id: string
        }
        Update: {
          actor_kind?: Database["public"]["Enums"]["actor_kind"]
          created_at?: string
          disabled_at?: string | null
          display_name?: string | null
          id?: string
          role?: Database["public"]["Enums"]["app_role"]
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      drop_old_analytics_partitions: {
        Args: { keep_months?: number }
        Returns: number
      }
      editorial_transition_allowed: {
        Args: {
          p_from: Database["public"]["Enums"]["editorial_state"]
          p_to: Database["public"]["Enums"]["editorial_state"]
        }
        Returns: boolean
      }
      ensure_analytics_partitions: {
        Args: { months_ahead?: number }
        Returns: undefined
      }
      is_staff: { Args: never; Returns: boolean }
      role_in: {
        Args: { p_roles: Database["public"]["Enums"]["app_role"][] }
        Returns: boolean
      }
      save_property: {
        Args: { p_expected_version: number; p_id: string; p_patch: Json }
        Returns: {
          address: string
          architect: string | null
          archived_at: string | null
          baths: number | null
          beds: number | null
          campaign_tier: Database["public"]["Enums"]["campaign_tier"]
          city: string
          coordinates: unknown
          country: string | null
          created_at: string
          created_by: string | null
          currency: string
          designer: string | null
          editorial_state: Database["public"]["Enums"]["editorial_state"]
          featured_rank: number | null
          first_published_at: string | null
          hero_image: string | null
          hero_rank: number | null
          id: string
          interior_sq_ft: number | null
          listing_url: string | null
          lot_acres: number | null
          market_slug: string
          neighborhood: string | null
          og_image_key: string | null
          place: string | null
          presented_by_owner: boolean
          preview_nonce: string
          price: number | null
          published_at: string | null
          region_slug: string | null
          representative_id: string | null
          search_text: unknown
          slug: string
          source: Database["public"]["Enums"]["submission_source"]
          state: string
          status: Database["public"]["Enums"]["listing_status"]
          story: string[]
          style: string | null
          submission_id: string | null
          taken_down_at: string | null
          title: string
          type: Database["public"]["Enums"]["property_type"]
          unpublish_reason: string | null
          unpublished_at: string | null
          updated_at: string
          updated_by: string | null
          version: number
          video: Json | null
          year_built: number | null
        }
        SetofOptions: {
          from: "*"
          to: "properties"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      submission_transition_allowed: {
        Args: {
          p_from: Database["public"]["Enums"]["submission_state"]
          p_to: Database["public"]["Enums"]["submission_state"]
        }
        Returns: boolean
      }
    }
    Enums: {
      accepted_state: "California" | "New York" | "Florida"
      actor_kind: "human" | "agent"
      app_role:
        | "chief_editor"
        | "managing_editor"
        | "visual_editor"
        | "media_ops"
        | "commercial"
        | "admin"
      campaign_tier: "Editorial" | "Feature" | "Reach" | "Campaign"
      channel_status: "none" | "planned" | "active" | "done"
      editorial_state:
        | "draft"
        | "review"
        | "agent_review"
        | "published"
        | "archived"
      exposure_package:
        | "The Feature"
        | "The Reach"
        | "The Campaign"
        | "Five Features"
        | "Not sure yet"
      inquiry_intent:
        | "showing"
        | "ask"
        | "similar"
        | "sell"
        | "invest"
        | "agent"
        | "general"
      inquiry_state: "new" | "in_progress" | "forwarded" | "closed"
      listing_status:
        | "Illustrative"
        | "Active"
        | "Off-market"
        | "Under offer"
        | "Sold"
      media_orientation: "landscape" | "portrait"
      payment_method: "invoice_manual" | "stripe"
      payment_status: "due" | "paid" | "waived" | "refunded"
      property_type:
        | "Estate"
        | "Residence"
        | "Townhouse"
        | "Waterfront"
        | "Farmhouse"
        | "Apartment"
        | "Penthouse"
      story_category: "Architecture" | "Interiors" | "Places" | "Stories"
      submission_source: "Editorial" | "Submission"
      submission_state:
        | "Submitted"
        | "Under Review"
        | "Accepted"
        | "Declined"
        | "Awaiting Assets"
        | "Invoice Issued"
        | "Scheduled"
        | "Published"
        | "Distribution Active"
        | "Completed"
        | "Withdrawn"
      submitter_kind: "agent" | "owner"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      accepted_state: ["California", "New York", "Florida"],
      actor_kind: ["human", "agent"],
      app_role: [
        "chief_editor",
        "managing_editor",
        "visual_editor",
        "media_ops",
        "commercial",
        "admin",
      ],
      campaign_tier: ["Editorial", "Feature", "Reach", "Campaign"],
      channel_status: ["none", "planned", "active", "done"],
      editorial_state: [
        "draft",
        "review",
        "agent_review",
        "published",
        "archived",
      ],
      exposure_package: [
        "The Feature",
        "The Reach",
        "The Campaign",
        "Five Features",
        "Not sure yet",
      ],
      inquiry_intent: [
        "showing",
        "ask",
        "similar",
        "sell",
        "invest",
        "agent",
        "general",
      ],
      inquiry_state: ["new", "in_progress", "forwarded", "closed"],
      listing_status: [
        "Illustrative",
        "Active",
        "Off-market",
        "Under offer",
        "Sold",
      ],
      media_orientation: ["landscape", "portrait"],
      payment_method: ["invoice_manual", "stripe"],
      payment_status: ["due", "paid", "waived", "refunded"],
      property_type: [
        "Estate",
        "Residence",
        "Townhouse",
        "Waterfront",
        "Farmhouse",
        "Apartment",
        "Penthouse",
      ],
      story_category: ["Architecture", "Interiors", "Places", "Stories"],
      submission_source: ["Editorial", "Submission"],
      submission_state: [
        "Submitted",
        "Under Review",
        "Accepted",
        "Declined",
        "Awaiting Assets",
        "Invoice Issued",
        "Scheduled",
        "Published",
        "Distribution Active",
        "Completed",
        "Withdrawn",
      ],
      submitter_kind: ["agent", "owner"],
    },
  },
} as const
