export const LogEvent = [
  "unhandled_error",
  "sentry_send_failed",
  "env_invalid",
  "env_optional_missing",
  "media_public_base_unset",
  "request",
  "public_read_stale",
  "stale_report_failed",
  "honeypot",
  "turnstile_unreachable",
  "event_pending",
  "analytics_store_failed",
  "client_error_report_failed",
  "webhook_forget_failed",
  "runner_beat_failed",
  "ops_health_failed",
  "meta_token_refresh_failed",
  "fanout_failed",
  "fanout_payload_invalid",
  "schedule_claim_failed",
  "schedule_not_implemented",
  "schedule_failed",
  "schedule_rollback_missed",
] as const;

export type LogEvent = (typeof LogEvent)[number];
