export const LogEvent = [
  "unhandled_error",
  "sentry_send_failed",
  "env_invalid",
  "env_optional_missing",
  "media_public_base_unset",
  "request",
  "public_read_stale",
  "stale_report_failed",
  "honeypot",
  "turnstile_unreachable",
  "event_pending",
  "analytics_store_failed",
  "client_error_report_failed",
  "webhook_forget_failed",
  "runner_beat_failed",
  "ops_health_failed",
  "meta_token_refresh_failed",
  "fanout_failed",
  "fanout_payload_invalid",
  "fanout_failure_unrecorded",
  "schedule_cron_invalid",
  "schedule_claim_failed",
  "schedule_failed",
  "schedule_rollback_missed",
  "keepwarm_disabled",
  "keepwarm_last_run_update_failed",
  "keepwarm_state_rpc_failed",
  "keepwarm_beat_failed",
  "keepwarm_liveness_rpc_failed",
  "keepwarm_tick",
  "keepwarm_env_missing",
  "send_link_limited",
  "auth_send_failed",
  "jwks_fetch_failed",
  "confirm_secret_missing",
  "alert_report_failed",
  "email_content_changed",
  "email_event_foreign_env",
  "resend_quota_daily",
  "social_dry_run",
  "thumbnail_sign_failed",
  "invoice_glyph_replaced",
  "decision_jobs_unread",
  // B7 step 14: the role write of a new auth account failed, and the account was deleted again (or not).
  "team_account_rolled_back",
] as const;

export type LogEvent = (typeof LogEvent)[number];
