// Writes src/templates/theme.gen.ts from the five colour tokens of src/styles/tokens.css (B5 step 1, G-007).
// Email HTML and the invoice PDF need literal colours, so they read this file and never a typed hex.
import { readFileSync, writeFileSync } from "node:fs";

const TOKENS = {
  background: "--background",
  foreground: "--foreground",
  secondary: "--secondary",
  mutedForeground: "--muted-foreground",
  accent: "--accent",
} as const;

type ThemeName = keyof typeof TOKENS;

const names = Object.keys(TOKENS).filter((name): name is ThemeName => name in TOKENS);

const hexOf = (css: string, token: string): string => {
  const match = new RegExp(`^\\s*${token}:\\s*(#[0-9a-fA-F]{6})\\s*;`, "m").exec(css);
  if (match?.[1] === undefined) throw new Error(`tokens.css has no six-digit hex for ${token}`);
  return match[1].toLowerCase();
};

const channel = (hex: string, from: number): number =>
  Number((parseInt(hex.slice(from, from + 2), 16) / 255).toFixed(4));

export function renderTheme(css: string): string {
  const hex = names.map((name) => [name, hexOf(css, TOKENS[name])] as const);
  const lines = [
    "// Generated by scripts/gen-theme.ts from src/styles/tokens.css. Do not edit.",
    "// Regenerate with: bun run scripts/gen-theme.ts",
    "",
    "export const themeHex = {",
    ...hex.map(([name, value]) => `  ${name}: "${value}",`),
    "} as const;",
    "",
    "/** The same colours as 0 to 1 triples, for pdf-lib. */",
    "export const themeRgb = {",
    ...hex.map(
      ([name, value]) =>
        `  ${name}: [${[1, 3, 5].map((from) => channel(value, from)).join(", ")}],`,
    ),
    "} as const;",
    "",
  ];
  return lines.join("\n");
}

if (import.meta.main) {
  const css = readFileSync(new URL("../src/styles/tokens.css", import.meta.url), "utf8");
  writeFileSync(new URL("../src/templates/theme.gen.ts", import.meta.url), renderTheme(css));
}
